import React, { useState, useEffect, useRef } from 'react';
import {
  Award,
  BookOpen,
  Sparkles,
  Clock,
  CheckCircle2,
  XCircle,
  HelpCircle,
  ArrowRight,
  ArrowLeft,
  RotateCcw,
  Volume2,
  VolumeX,
  Play,
  Pause,
  Flag,
  Bookmark,
  Share2,
  ChevronDown,
  ChevronUp,
  AlertCircle,
  Layers,
  Filter,
  Eye,
  EyeOff,
  Zap,
} from 'lucide-react';
import { CURATED_EXAMS, ExamTest, ExamQuestion, ExamType, ExamPart } from '../data/examData';
import { UserProfileProgress, VocabWord } from '../types';
import { speak, stopSpeech } from '../utils/speech';

interface ToeicIeltsExamHubProps {
  profile: UserProfileProgress;
  onUpdateProfile: (profile: UserProfileProgress) => void;
  isDarkMode?: boolean;
}

export const ToeicIeltsExamHub: React.FC<ToeicIeltsExamHubProps> = ({
  profile,
  onUpdateProfile,
  isDarkMode = false,
}) => {
  // Mode: 'library' (danh sách đề) | 'create' (tạo đề AI) | 'exam' (làm bài) | 'result' (kết quả)
  const [viewMode, setViewMode] = useState<'library' | 'create' | 'exam' | 'result'>('library');
  const [selectedExamType, setSelectedExamType] = useState<ExamType | 'ALL'>('ALL');
  const [activeTest, setActiveTest] = useState<ExamTest | null>(null);

  // Exam taking state
  const [userAnswers, setUserAnswers] = useState<Record<number, string>>({});
  const [flaggedQuestions, setFlaggedQuestions] = useState<Record<number, boolean>>({});
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState<number>(0);
  const [eliminatedOptions, setEliminatedOptions] = useState<Record<string, boolean>>({}); // e.g. "q1-A": true
  const [timeLeft, setTimeLeft] = useState<number>(0);
  const [isTimerPaused, setIsTimerPaused] = useState<boolean>(false);
  const [isUntimed, setIsUntimed] = useState<boolean>(false);

  // Audio simulation state (for Listening parts)
  const [isPlayingAudio, setIsPlayingAudio] = useState<boolean>(false);
  const [showScript, setShowScript] = useState<boolean>(false);

  // AI Generator state
  const [genExamType, setGenExamType] = useState<ExamType>('TOEIC');
  const [genPart, setGenPart] = useState<ExamPart>('TOEIC_PART5');
  const [genTargetLevel, setGenTargetLevel] = useState<string>('750+');
  const [genTopic, setGenTopic] = useState<string>('Công sở & Đàm phán kinh doanh quốc tế');
  const [genQuestionCount, setGenQuestionCount] = useState<number>(5);
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [genError, setGenError] = useState<string | null>(null);

  // Bookmark notification toast state
  const [savedVocabFeedback, setSavedVocabFeedback] = useState<string | null>(null);

  // Custom exams generated by AI during session
  const [customExams, setCustomExams] = useState<ExamTest[]>([]);

  // Combined exams list
  const allExams = [...customExams, ...CURATED_EXAMS];

  // Filtered exams
  const filteredExams = allExams.filter((exam) => {
    if (selectedExamType === 'ALL') return true;
    return exam.examType === selectedExamType;
  });

  // Timer effect during exam
  useEffect(() => {
    if (viewMode !== 'exam' || isUntimed || isTimerPaused || timeLeft <= 0) return;

    const timer = setInterval(() => {
      setTimeLeft((prev) => {
        if (prev <= 1) {
          clearInterval(timer);
          handleSubmitExam();
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(timer);
  }, [viewMode, isUntimed, isTimerPaused, timeLeft]);

  // Clean up audio on unmount or view change
  useEffect(() => {
    return () => {
      stopSpeech();
    };
  }, [viewMode]);

  // Start a test
  const handleStartTest = (test: ExamTest) => {
    setActiveTest(test);
    setUserAnswers({});
    setFlaggedQuestions({});
    setCurrentQuestionIndex(0);
    setEliminatedOptions({});
    setTimeLeft(test.timeLimitMinutes * 60);
    setIsTimerPaused(false);
    setIsUntimed(false);
    setIsPlayingAudio(false);
    setShowScript(false);
    setViewMode('exam');
  };

  // Submit test
  const handleSubmitExam = () => {
    stopSpeech();
    setIsPlayingAudio(false);
    setViewMode('result');
  };

  // Toggle option strike-through
  const toggleEliminate = (key: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setEliminatedOptions((prev) => ({
      ...prev,
      [key]: !prev[key],
    }));
  };

  // Select answer
  const handleSelectAnswer = (questionId: number, optionLetter: string) => {
    setUserAnswers((prev) => ({
      ...prev,
      [questionId]: optionLetter,
    }));
  };

  // Toggle flag
  const toggleFlag = (questionId: number) => {
    setFlaggedQuestions((prev) => ({
      ...prev,
      [questionId]: !prev[questionId],
    }));
  };

  // Play audio script
  const handlePlayAudio = () => {
    if (!activeTest?.audioScript) return;

    if (isPlayingAudio) {
      stopSpeech();
      setIsPlayingAudio(false);
    } else {
      setIsPlayingAudio(true);
      const isUK = activeTest.examType === 'IELTS';
      speak(
        activeTest.audioScript,
        'en',
        0.95,
        () => setIsPlayingAudio(false),
        isUK ? 'uk' : 'us'
      );
    }
  };

  // Generate test with AI
  const handleGenerateAIExam = async () => {
    setIsGenerating(true);
    setGenError(null);

    try {
      const response = await fetch('/api/generate-exam', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          examType: genExamType,
          part: genPart,
          targetLevel: genTargetLevel,
          topic: genTopic,
          questionCount: genQuestionCount,
        }),
      });

      if (!response.ok) {
        throw new Error('Không thể kết nối với máy chủ AI');
      }

      const data: ExamTest = await response.json();
      if (!data || !data.questions || data.questions.length === 0) {
        throw new Error('Định dạng đề thi nhận về không hợp lệ');
      }

      // Add unique ID and tag
      const newExam: ExamTest = {
        ...data,
        id: `ai-${Date.now()}`,
        subtitle: `Tạo tự động bởi AI - ${genTopic}`,
        tags: ['AI Generated', data.part, `${genQuestionCount} câu`],
      };

      setCustomExams((prev) => [newExam, ...prev]);
      handleStartTest(newExam);
    } catch (err: any) {
      console.error('Error generating exam:', err);
      setGenError(err?.message || 'Có lỗi xảy ra khi tạo đề thi bằng AI. Vui lòng thử lại.');
    } finally {
      setIsGenerating(false);
    }
  };

  // Save vocabulary to profile notebook
  const handleSaveVocabToNotebook = (wordText: string, meaningText: string, phoneticText: string) => {
    const wordId = `vocab-exam-${Date.now()}-${Math.random().toString(36).substr(2, 4)}`;
    const newProgress = { ...profile.wordsProgress };

    newProgress[wordId] = {
      wordId,
      status: 'learning',
      repetitions: 1,
      easeFactor: 2.5,
      intervalDays: 1,
      nextReviewDate: Date.now() + 86400000,
      correctCount: 1,
      incorrectCount: 0,
      lastReviewed: Date.now(),
      isBookmarked: true,
      bestSpeechScore: 100,
    };

    onUpdateProfile({
      ...profile,
      wordsProgress: newProgress,
    });

    setSavedVocabFeedback(`Đã lưu "${wordText}" vào Sổ tay từ vựng!`);
    setTimeout(() => setSavedVocabFeedback(null), 3000);
  };

  // Format timer seconds to mm:ss
  const formatTime = (secs: number) => {
    const mins = Math.floor(secs / 60);
    const remSecs = secs % 60;
    return `${mins.toString().padStart(2, '0')}:${remSecs.toString().padStart(2, '0')}`;
  };

  // Compute exam score
  const calculateResults = () => {
    if (!activeTest) return { correctCount: 0, totalCount: 0, percentage: 0, scaledScore: '' };

    let correctCount = 0;
    activeTest.questions.forEach((q) => {
      const userAns = userAnswers[q.id]?.toUpperCase();
      const correct = q.correctAnswer.toUpperCase();
      if (userAns === correct) {
        correctCount++;
      }
    });

    const totalCount = activeTest.questions.length;
    const percentage = Math.round((correctCount / totalCount) * 100);

    let scaledScore = '';
    if (activeTest.examType === 'TOEIC') {
      // Scale approximation to 495 / 990
      const approxPoints = Math.round((correctCount / totalCount) * 450 + 50);
      scaledScore = `Ước tính: ~${approxPoints} / 495 pts`;
    } else {
      // IELTS Band approximation
      let band = 5.0;
      if (percentage >= 90) band = 8.5;
      else if (percentage >= 80) band = 7.5;
      else if (percentage >= 70) band = 7.0;
      else if (percentage >= 60) band = 6.5;
      else if (percentage >= 50) band = 6.0;
      else band = 5.5;
      scaledScore = `Ước tính: Band ${band.toFixed(1)}`;
    }

    return { correctCount, totalCount, percentage, scaledScore };
  };

  // =========================================================================
  // VIEW 1: LIBRARY OF EXAMS
  // =========================================================================
  if (viewMode === 'library') {
    return (
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8 animate-in fade-in duration-300">
        {/* Banner Header */}
        <div
          className={`p-6 sm:p-8 rounded-3xl border relative overflow-hidden transition-all ${
            isDarkMode
              ? 'bg-gradient-to-r from-slate-900 via-indigo-950/60 to-slate-900 border-indigo-900/50 shadow-xl'
              : 'bg-gradient-to-r from-indigo-50 via-sky-50 to-white border-indigo-100 shadow-md'
          }`}
        >
          <div className="relative z-10 max-w-3xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-bold bg-indigo-600/10 text-indigo-600 dark:text-indigo-400 mb-3 border border-indigo-500/20">
              <Award className="w-3.5 h-3.5" />
              <span>Phòng Thi & Luyện Đề Chuẩn ETS & Cambridge (Theo format STUDY4)</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight">
              Luyện Thi TOEIC & IELTS Chuẩn Quốc Tế
            </h1>
            <p className="mt-2 text-xs sm:text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
              Trải nghiệm các đề thi mẫu chính thức được biên soạn theo đúng cấu trúc ETS TOEIC (Part 1 - 7) và Cambridge IELTS (Reading & Listening). Tích hợp đồng hồ thi thật, giải thích chi tiết đáp án và hệ thống <strong>AI tự tạo đề thi theo yêu cầu</strong>.
            </p>

            <div className="mt-6 flex flex-wrap gap-3">
              <button
                onClick={() => setViewMode('create')}
                className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-indigo-600 to-sky-600 text-white font-bold text-xs sm:text-sm shadow-lg shadow-indigo-600/20 hover:scale-105 active:scale-95 transition"
              >
                <Sparkles className="w-4 h-4 text-amber-300" />
                <span>Tạo Đề Thi Mới Bằng AI</span>
              </button>
              <div className="flex items-center gap-2 text-xs text-slate-500 dark:text-slate-400 py-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                <span>Có sẵn {allExams.length} bộ đề mẫu chuẩn chỉnh</span>
              </div>
            </div>
          </div>

          <div className="absolute -right-8 -bottom-8 opacity-10 dark:opacity-20 text-indigo-500 hidden md:block">
            <Award className="w-64 h-64" />
          </div>
        </div>

        {/* Filter Bar */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2 p-1 rounded-2xl border bg-slate-100 dark:bg-slate-900 border-slate-200 dark:border-slate-800 w-full sm:w-auto">
            <button
              onClick={() => setSelectedExamType('ALL')}
              className={`flex-1 sm:flex-initial px-4 py-2 rounded-xl text-xs font-bold transition ${
                selectedExamType === 'ALL'
                  ? 'bg-white dark:bg-slate-800 text-indigo-600 dark:text-indigo-400 shadow-xs'
                  : 'text-slate-600 dark:text-slate-400 hover:text-slate-900'
              }`}
            >
              Tất cả đề ({allExams.length})
            </button>
            <button
              onClick={() => setSelectedExamType('TOEIC')}
              className={`flex-1 sm:flex-initial px-4 py-2 rounded-xl text-xs font-bold transition flex items-center justify-center gap-1.5 ${
                selectedExamType === 'TOEIC'
                  ? 'bg-rose-500 text-white shadow-xs'
                  : 'text-slate-600 dark:text-slate-400 hover:text-rose-500'
              }`}
            >
              <span>TOEIC ETS</span>
            </button>
            <button
              onClick={() => setSelectedExamType('IELTS')}
              className={`flex-1 sm:flex-initial px-4 py-2 rounded-xl text-xs font-bold transition flex items-center justify-center gap-1.5 ${
                selectedExamType === 'IELTS'
                  ? 'bg-sky-600 text-white shadow-xs'
                  : 'text-slate-600 dark:text-slate-400 hover:text-sky-500'
              }`}
            >
              <span>IELTS Academic</span>
            </button>
          </div>

          <button
            onClick={() => setViewMode('create')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl border text-xs font-semibold transition ${
              isDarkMode
                ? 'bg-slate-800 border-slate-700 text-slate-300 hover:border-indigo-500'
                : 'bg-white border-slate-200 text-slate-700 hover:border-indigo-400'
            }`}
          >
            <Zap className="w-3.5 h-3.5 text-amber-500" />
            <span>Tùy chỉnh đề ôn luyện riêng</span>
          </button>
        </div>

        {/* Exam Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredExams.map((exam) => (
            <div
              key={exam.id}
              className={`group flex flex-col justify-between p-6 rounded-3xl border transition-all duration-200 hover:-translate-y-1 hover:shadow-xl ${
                isDarkMode
                  ? 'bg-slate-900 border-slate-800 hover:border-indigo-600/60 shadow-lg'
                  : 'bg-white border-slate-200 hover:border-indigo-300 shadow-sm'
              }`}
            >
              <div>
                <div className="flex items-center justify-between gap-2 mb-3">
                  <span
                    className={`px-2.5 py-1 rounded-lg text-[11px] font-black tracking-wider uppercase ${
                      exam.examType === 'TOEIC'
                        ? 'bg-rose-500/10 text-rose-600 dark:text-rose-400 border border-rose-500/20'
                        : 'bg-sky-500/10 text-sky-600 dark:text-sky-400 border border-sky-500/20'
                    }`}
                  >
                    {exam.examType} &bull; {exam.part.replace('_', ' ')}
                  </span>
                  <span className="text-[11px] font-semibold text-slate-500 flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    {exam.timeLimitMinutes} phút
                  </span>
                </div>

                <h3 className="font-extrabold text-base line-clamp-2 group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors">
                  {exam.title}
                </h3>
                <p className="mt-2 text-xs text-slate-500 dark:text-slate-400 line-clamp-2">
                  {exam.subtitle}
                </p>

                <div className="mt-4 flex flex-wrap gap-1.5">
                  <span className="px-2 py-0.5 rounded-md text-[10px] font-semibold bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-300">
                    🎯 Mục tiêu: {exam.targetLevel}
                  </span>
                  <span className="px-2 py-0.5 rounded-md text-[10px] font-semibold bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300">
                    📝 {exam.questions.length} câu hỏi
                  </span>
                  {exam.audioScript && (
                    <span className="px-2 py-0.5 rounded-md text-[10px] font-semibold bg-amber-50 dark:bg-amber-950/60 text-amber-600 dark:text-amber-400 flex items-center gap-1">
                      <Volume2 className="w-3 h-3" /> Audio Listening
                    </span>
                  )}
                </div>
              </div>

              <div className="mt-6 pt-4 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between">
                <div className="text-[11px] text-slate-400">
                  {exam.tags.slice(0, 2).join(' • ')}
                </div>
                <button
                  onClick={() => handleStartTest(exam)}
                  className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs transition shadow-sm"
                >
                  <span>Bắt đầu thi</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  // =========================================================================
  // VIEW 2: AI EXAM GENERATOR (TẠO ĐỀ THI TÙY BIẾN)
  // =========================================================================
  if (viewMode === 'create') {
    return (
      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8 space-y-6 animate-in fade-in duration-300">
        <button
          onClick={() => setViewMode('library')}
          className="flex items-center gap-2 text-xs font-bold text-slate-500 hover:text-indigo-600 transition"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Quay lại Thư viện đề</span>
        </button>

        <div
          className={`p-6 sm:p-8 rounded-3xl border shadow-xl ${
            isDarkMode ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200'
          }`}
        >
          <div className="flex items-center gap-3 pb-6 border-b border-slate-200 dark:border-slate-800">
            <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-indigo-600 to-sky-600 flex items-center justify-center text-white shadow-md">
              <Sparkles className="w-6 h-6 text-amber-300" />
            </div>
            <div>
              <h2 className="text-xl font-black">AI Tạo Đề Thi Chuẩn Quốc Tế Theo Yêu Cầu</h2>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
                Mô phỏng đề thi thực chiến theo tiêu chuẩn ETS TOEIC & Cambridge IELTS cho mọi cấp độ
              </p>
            </div>
          </div>

          {genError && (
            <div className="mt-4 p-4 rounded-2xl bg-rose-500/10 border border-rose-500/30 text-rose-600 dark:text-rose-400 text-xs flex items-start gap-2">
              <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
              <span>{genError}</span>
            </div>
          )}

          <div className="mt-6 space-y-6">
            {/* Step 1: Chọn kỳ thi */}
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                1. Chọn Kỳ Thi Mục Tiêu
              </label>
              <div className="grid grid-cols-2 gap-4">
                <button
                  type="button"
                  onClick={() => {
                    setGenExamType('TOEIC');
                    setGenPart('TOEIC_PART5');
                    setGenTargetLevel('750+');
                  }}
                  className={`p-4 rounded-2xl border text-left transition-all ${
                    genExamType === 'TOEIC'
                      ? 'border-rose-500 bg-rose-500/5 ring-2 ring-rose-500/20'
                      : 'border-slate-200 dark:border-slate-800 hover:border-slate-300'
                  }`}
                >
                  <div className="font-black text-rose-600 dark:text-rose-400 text-base">TOEIC ETS</div>
                  <div className="text-xs text-slate-500 mt-1">
                    Trọng tâm giao tiếp quốc tế, thương mại & môi trường làm việc công sở
                  </div>
                </button>

                <button
                  type="button"
                  onClick={() => {
                    setGenExamType('IELTS');
                    setGenPart('IELTS_READING');
                    setGenTargetLevel('Band 7.0 - 7.5');
                  }}
                  className={`p-4 rounded-2xl border text-left transition-all ${
                    genExamType === 'IELTS'
                      ? 'border-sky-500 bg-sky-500/5 ring-2 ring-sky-500/20'
                      : 'border-slate-200 dark:border-slate-800 hover:border-slate-300'
                  }`}
                >
                  <div className="font-black text-sky-600 dark:text-sky-400 text-base">IELTS Academic</div>
                  <div className="text-xs text-slate-500 mt-1">
                    Trọng tâm học thuật chuyên sâu, phân tích logic, True/False/Not Given
                  </div>
                </button>
              </div>
            </div>

            {/* Step 2: Chọn Phần thi / Kỹ năng */}
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                2. Chọn Phần Thi (Part / Section)
              </label>
              {genExamType === 'TOEIC' ? (
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                  {[
                    { id: 'TOEIC_PART5', name: 'Part 5: Điền từ vào câu (Ngữ pháp & Từ vựng)' },
                    { id: 'TOEIC_PART6', name: 'Part 6: Điền đoạn văn (Text Completion)' },
                    { id: 'TOEIC_PART7', name: 'Part 7: Đọc hiểu văn bản (Email, Memo, Article)' },
                    { id: 'TOEIC_PART1', name: 'Part 1: Mô tả hình ảnh (Photographs)' },
                    { id: 'TOEIC_PART2', name: 'Part 2: Hỏi & Đáp ngắn (Question-Response)' },
                    { id: 'TOEIC_MINI_TEST', name: 'Mini-Test tổng hợp các dạng' },
                  ].map((p) => (
                    <button
                      key={p.id}
                      type="button"
                      onClick={() => setGenPart(p.id as ExamPart)}
                      className={`p-3 rounded-xl border text-left text-xs font-medium transition ${
                        genPart === p.id
                          ? 'border-indigo-600 bg-indigo-50 dark:bg-indigo-950/60 text-indigo-700 dark:text-indigo-300 font-bold'
                          : 'border-slate-200 dark:border-slate-800 hover:border-slate-300'
                      }`}
                    >
                      {p.name}
                    </button>
                  ))}
                </div>
              ) : (
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                  {[
                    { id: 'IELTS_READING', name: 'Reading: Bài đọc học thuật & True/False/NG' },
                    { id: 'IELTS_LISTENING', name: 'Listening: Audio Script & Form Completion' },
                    { id: 'IELTS_WRITING', name: 'Writing: Đề Task 1/2 kèm dàn ý Band 8+' },
                    { id: 'IELTS_SPEAKING', name: 'Speaking: Part 2 Cue Card & Câu hỏi Part 3' },
                    { id: 'IELTS_MINI_TEST', name: 'IELTS Mini Practice Test' },
                  ].map((p) => (
                    <button
                      key={p.id}
                      type="button"
                      onClick={() => setGenPart(p.id as ExamPart)}
                      className={`p-3 rounded-xl border text-left text-xs font-medium transition ${
                        genPart === p.id
                          ? 'border-indigo-600 bg-indigo-50 dark:bg-indigo-950/60 text-indigo-700 dark:text-indigo-300 font-bold'
                          : 'border-slate-200 dark:border-slate-800 hover:border-slate-300'
                      }`}
                    >
                      {p.name}
                    </button>
                  ))}
                </div>
              )}
            </div>

            {/* Step 3: Target Level & Topic */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                  3. Mức Điểm Mục Tiêu (Target Score)
                </label>
                <select
                  value={genTargetLevel}
                  onChange={(e) => setGenTargetLevel(e.target.value)}
                  className={`w-full p-3 rounded-xl border text-xs font-bold ${
                    isDarkMode ? 'bg-slate-800 border-slate-700 text-white' : 'bg-slate-50 border-slate-200'
                  }`}
                >
                  {genExamType === 'TOEIC' ? (
                    <>
                      <option value="500 - 650 (Cơ bản - Trung cấp)">500 - 650 (Cơ bản - Trung cấp)</option>
                      <option value="700 - 850 (Nâng cao công sở)">700 - 850 (Nâng cao công sở)</option>
                      <option value="900+ (Chuyên gia thành thạo)">900+ (Chuyên gia thành thạo)</option>
                    </>
                  ) : (
                    <>
                      <option value="Band 5.5 - 6.5 (Competent User)">Band 5.5 - 6.5 (Competent User)</option>
                      <option value="Band 7.0 - 8.0 (Good User)">Band 7.0 - 8.0 (Good User)</option>
                      <option value="Band 8.5+ (Expert User)">Band 8.5+ (Expert User)</option>
                    </>
                  )}
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                  4. Số Lượng Câu Hỏi
                </label>
                <div className="flex gap-2">
                  {[5, 10, 15].map((cnt) => (
                    <button
                      key={cnt}
                      type="button"
                      onClick={() => setGenQuestionCount(cnt)}
                      className={`flex-1 py-2.5 rounded-xl border text-xs font-bold transition ${
                        genQuestionCount === cnt
                          ? 'bg-indigo-600 text-white border-indigo-600 shadow-sm'
                          : 'border-slate-200 dark:border-slate-800 hover:border-slate-300'
                      }`}
                    >
                      {cnt} câu
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* Step 4: Topic */}
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                5. Chủ Đề Bài Thi
              </label>
              <input
                type="text"
                value={genTopic}
                onChange={(e) => setGenTopic(e.target.value)}
                placeholder="Ví dụ: Công nghệ trí tuệ nhân tạo, Quản trị nhân sự, Biến đổi khí hậu..."
                className={`w-full p-3 rounded-xl border text-xs ${
                  isDarkMode ? 'bg-slate-800 border-slate-700 text-white' : 'bg-slate-50 border-slate-200'
                }`}
              />
              <div className="mt-2 flex flex-wrap gap-1.5 text-[11px] text-slate-500">
                <span>Gợi ý:</span>
                {[
                  'Tài chính & Ngân hàng',
                  'Du lịch & Khách sạn',
                  'Khoa học Môi trường',
                  'Đổi mới Công nghệ',
                  'Thương mại Điện tử',
                ].map((s) => (
                  <button
                    key={s}
                    type="button"
                    onClick={() => setGenTopic(s)}
                    className="underline hover:text-indigo-600 cursor-pointer"
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>
          </div>

          <div className="mt-8 pt-6 border-t border-slate-200 dark:border-slate-800 flex items-center justify-end gap-3">
            <button
              onClick={() => setViewMode('library')}
              className="px-5 py-2.5 rounded-xl text-xs font-bold text-slate-500 hover:text-slate-800 transition"
            >
              Hủy
            </button>
            <button
              onClick={handleGenerateAIExam}
              disabled={isGenerating}
              className="flex items-center gap-2 px-6 py-3 rounded-xl bg-gradient-to-r from-indigo-600 to-sky-600 text-white font-bold text-xs sm:text-sm shadow-xl shadow-indigo-600/30 hover:scale-105 active:scale-95 transition disabled:opacity-50"
            >
              {isGenerating ? (
                <>
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  <span>AI Đang Soạn Đề Chuẩn ETS/IELTS...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 text-amber-300" />
                  <span>⚡ Tạo Đề Thi & Vào Phòng Thi Ngay</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    );
  }

  // =========================================================================
  // VIEW 3: COMPUTER-BASED EXAM INTERFACE (PHÒNG THI MÁY TÍNH)
  // =========================================================================
  if (viewMode === 'exam' && activeTest) {
    const currentQ = activeTest.questions[currentQuestionIndex];
    const totalQuestions = activeTest.questions.length;
    const answeredCount = Object.keys(userAnswers).length;

    return (
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6 animate-in fade-in duration-300">
        {/* Exam Navigation Header Bar */}
        <div
          className={`p-4 rounded-2xl border flex flex-wrap items-center justify-between gap-4 shadow-sm sticky top-20 z-30 ${
            isDarkMode ? 'bg-slate-900/95 backdrop-blur-md border-slate-800' : 'bg-white/95 backdrop-blur-md border-slate-200'
          }`}
        >
          <div className="flex items-center gap-3">
            <span
              className={`px-2.5 py-1 rounded-lg text-xs font-black uppercase ${
                activeTest.examType === 'TOEIC'
                  ? 'bg-rose-500 text-white'
                  : 'bg-sky-600 text-white'
              }`}
            >
              {activeTest.examType}
            </span>
            <div>
              <h2 className="font-extrabold text-sm line-clamp-1">{activeTest.title}</h2>
              <p className="text-[11px] text-slate-500">
                Câu {currentQuestionIndex + 1} / {totalQuestions} &bull; Đã làm {answeredCount}/{totalQuestions} câu
              </p>
            </div>
          </div>

          {/* Timer & Controls */}
          <div className="flex items-center gap-3">
            {!isUntimed ? (
              <div
                className={`flex items-center gap-2 px-3.5 py-1.5 rounded-xl border text-xs font-mono font-bold ${
                  timeLeft < 180
                    ? 'bg-rose-50 text-rose-600 border-rose-300 animate-pulse'
                    : isDarkMode
                    ? 'bg-slate-800 border-slate-700 text-amber-400'
                    : 'bg-amber-50 border-amber-200 text-amber-700'
                }`}
              >
                <Clock className="w-4 h-4" />
                <span>{formatTime(timeLeft)}</span>
                <button
                  onClick={() => setIsTimerPaused(!isTimerPaused)}
                  title={isTimerPaused ? 'Tiếp tục' : 'Tạm dừng'}
                  className="opacity-75 hover:opacity-100 text-xs ml-1"
                >
                  {isTimerPaused ? '▶' : '⏸'}
                </button>
              </div>
            ) : (
              <div className="text-xs font-semibold text-slate-400 px-3 py-1.5 rounded-xl border border-dashed">
                Luyện tập tự do (Không giới hạn giờ)
              </div>
            )}

            <button
              onClick={() => setIsUntimed(!isUntimed)}
              className="text-[11px] text-slate-500 hover:text-indigo-600 underline"
            >
              {isUntimed ? 'Bật bấm giờ' : 'Tắt giờ'}
            </button>

            <button
              onClick={handleSubmitExam}
              className="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs transition shadow-md shadow-emerald-600/20"
            >
              Nộp bài thi
            </button>
          </div>
        </div>

        {/* Question Palette (Bảng chọn câu hỏi nhanh) */}
        <div
          className={`p-3 rounded-2xl border flex flex-wrap items-center gap-2 ${
            isDarkMode ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200'
          }`}
        >
          <span className="text-[11px] font-bold text-slate-400 mr-1 hidden sm:inline">
            Danh sách câu:
          </span>
          {activeTest.questions.map((q, idx) => {
            const isAnswered = !!userAnswers[q.id];
            const isCurrent = idx === currentQuestionIndex;
            const isFlagged = !!flaggedQuestions[q.id];

            return (
              <button
                key={q.id}
                onClick={() => setCurrentQuestionIndex(idx)}
                className={`w-8 h-8 rounded-lg text-xs font-bold relative transition-all ${
                  isCurrent
                    ? 'ring-2 ring-indigo-500 ring-offset-2'
                    : ''
                } ${
                  isAnswered
                    ? 'bg-indigo-600 text-white'
                    : isDarkMode
                    ? 'bg-slate-800 text-slate-300 hover:bg-slate-700'
                    : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
                }`}
              >
                {idx + 1}
                {isFlagged && (
                  <span className="absolute -top-1 -right-1 w-2.5 h-2.5 bg-amber-400 rounded-full border border-white" />
                )}
              </button>
            );
          })}
        </div>

        {/* Main Content Area (Split Pane if Passage or Audio) */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
          {/* Left Column: Passage or Audio Player (if applicable) */}
          {(activeTest.passage || activeTest.audioScript || activeTest.imageScene) && (
            <div
              className={`lg:col-span-6 p-6 rounded-3xl border space-y-4 max-h-[650px] overflow-y-auto ${
                isDarkMode ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200 shadow-sm'
              }`}
            >
              {activeTest.passageTitle && (
                <div className="pb-3 border-b border-slate-200 dark:border-slate-800">
                  <span className="text-[10px] font-extrabold uppercase tracking-wider text-indigo-500">
                    Bài đọc đoạn văn (Reading Passage)
                  </span>
                  <h3 className="text-base font-extrabold text-slate-900 dark:text-white mt-1">
                    {activeTest.passageTitle}
                  </h3>
                </div>
              )}

              {/* Audio Player for Listening */}
              {activeTest.audioScript && (
                <div className="p-4 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 space-y-3">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <div className="p-2 rounded-xl bg-indigo-600 text-white">
                        <Volume2 className="w-5 h-5" />
                      </div>
                      <div>
                        <div className="font-bold text-xs">Audio Listening Simulation</div>
                        <div className="text-[11px] text-slate-500">
                          {activeTest.examType === 'IELTS' ? 'British Accent (UK)' : 'American Accent (US)'}
                        </div>
                      </div>
                    </div>

                    <button
                      onClick={handlePlayAudio}
                      className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold text-white transition ${
                        isPlayingAudio ? 'bg-rose-600 hover:bg-rose-700' : 'bg-indigo-600 hover:bg-indigo-700'
                      }`}
                    >
                      {isPlayingAudio ? (
                        <>
                          <Pause className="w-4 h-4" />
                          <span>Dừng nghe</span>
                        </>
                      ) : (
                        <>
                          <Play className="w-4 h-4" />
                          <span>Phát Audio</span>
                        </>
                      )}
                    </button>
                  </div>

                  <div className="flex items-center justify-between pt-2 border-t border-indigo-500/20 text-xs">
                    <button
                      onClick={() => setShowScript(!showScript)}
                      className="text-indigo-600 dark:text-indigo-400 font-semibold flex items-center gap-1 hover:underline"
                    >
                      {showScript ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                      <span>{showScript ? 'Ẩn Audio Transcript' : 'Xem trước Audio Transcript'}</span>
                    </button>
                    <span className="text-[10px] text-slate-400">Web Speech API High-Fidelity TTS</span>
                  </div>

                  {showScript && (
                    <div className="p-3 rounded-xl bg-white dark:bg-slate-900 border text-xs text-slate-700 dark:text-slate-300 whitespace-pre-line leading-relaxed italic">
                      {activeTest.audioScript}
                    </div>
                  )}
                </div>
              )}

              {/* Image Scene description for TOEIC Part 1 */}
              {activeTest.imageScene && (
                <div className="p-4 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-xs text-slate-700 dark:text-slate-300">
                  <span className="font-bold text-amber-500 block mb-1">🖼 Mô tả bối cảnh hình ảnh:</span>
                  {activeTest.imageScene}
                </div>
              )}

              {/* Reading Passage Body */}
              {activeTest.passage && (
                <div className="text-xs sm:text-sm text-slate-700 dark:text-slate-300 leading-relaxed whitespace-pre-line font-serif selection:bg-indigo-200">
                  {activeTest.passage}
                </div>
              )}
            </div>
          )}

          {/* Right Column: Question & Options */}
          <div
            className={`${
              activeTest.passage || activeTest.audioScript || activeTest.imageScene
                ? 'lg:col-span-6'
                : 'lg:col-span-12'
            } p-6 sm:p-8 rounded-3xl border shadow-sm space-y-6 ${
              isDarkMode ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200'
            }`}
          >
            {/* Question Header */}
            <div className="flex items-center justify-between gap-3 pb-4 border-b border-slate-200 dark:border-slate-800">
              <span className="text-xs font-black text-indigo-600 dark:text-indigo-400">
                CÂU HỎI SỐ {currentQuestionIndex + 1}
              </span>
              <button
                onClick={() => toggleFlag(currentQ.id)}
                className={`flex items-center gap-1.5 px-3 py-1 rounded-lg text-xs font-semibold transition ${
                  flaggedQuestions[currentQ.id]
                    ? 'bg-amber-500 text-white'
                    : 'text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 bg-slate-100 dark:bg-slate-800'
                }`}
              >
                <Flag className="w-3.5 h-3.5" />
                <span>{flaggedQuestions[currentQ.id] ? 'Đã cắm cờ' : 'Cắm cờ xem lại'}</span>
              </button>
            </div>

            {/* Question Text */}
            <div className="text-sm sm:text-base font-bold text-slate-900 dark:text-white leading-relaxed">
              {currentQ.question}
            </div>

            {/* Hint for strikethrough */}
            <div className="text-[11px] text-slate-400 flex items-center gap-1">
              <span>Mẹo: Nhấp vào nút gạch (✕) bên cạnh đáp án để loại trừ phương án sai.</span>
            </div>

            {/* Options List */}
            <div className="space-y-3">
              {currentQ.options.map((opt, oIdx) => {
                const letter = opt.startsWith('(') ? opt.charAt(1) : String.fromCharCode(65 + oIdx);
                const isSelected = userAnswers[currentQ.id]?.toUpperCase() === letter.toUpperCase();
                const strikeKey = `q${currentQ.id}-${letter}`;
                const isEliminated = !!eliminatedOptions[strikeKey];

                return (
                  <div
                    key={opt}
                    onClick={() => handleSelectAnswer(currentQ.id, letter)}
                    className={`flex items-center justify-between p-4 rounded-2xl border cursor-pointer transition-all ${
                      isSelected
                        ? 'border-indigo-600 bg-indigo-50/80 dark:bg-indigo-950/60 ring-2 ring-indigo-500/30'
                        : isEliminated
                        ? 'opacity-40 line-through bg-slate-50 dark:bg-slate-900/40 border-slate-200 dark:border-slate-800'
                        : 'border-slate-200 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700'
                    }`}
                  >
                    <div className="flex items-center gap-3 flex-1 min-w-0 pr-2">
                      <div
                        className={`w-7 h-7 rounded-xl flex items-center justify-center font-bold text-xs shrink-0 ${
                          isSelected
                            ? 'bg-indigo-600 text-white'
                            : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400'
                        }`}
                      >
                        {letter}
                      </div>
                      <span className="text-xs sm:text-sm font-medium">{opt}</span>
                    </div>

                    <button
                      type="button"
                      title="Gạch loại trừ phương án này"
                      onClick={(e) => toggleEliminate(strikeKey, e)}
                      className="p-1 text-slate-400 hover:text-rose-500 rounded-md hover:bg-slate-100 dark:hover:bg-slate-800 transition"
                    >
                      ✕
                    </button>
                  </div>
                );
              })}
            </div>

            {/* Footer Navigation Buttons */}
            <div className="pt-6 border-t border-slate-200 dark:border-slate-800 flex items-center justify-between gap-3">
              <button
                disabled={currentQuestionIndex === 0}
                onClick={() => setCurrentQuestionIndex((prev) => Math.max(0, prev - 1))}
                className="flex items-center gap-1.5 px-4 py-2.5 rounded-xl border text-xs font-bold disabled:opacity-30 transition"
              >
                <ArrowLeft className="w-4 h-4" />
                <span>Câu trước</span>
              </button>

              <div className="text-xs text-slate-400">
                {currentQuestionIndex + 1} / {totalQuestions}
              </div>

              {currentQuestionIndex < totalQuestions - 1 ? (
                <button
                  onClick={() => setCurrentQuestionIndex((prev) => Math.min(totalQuestions - 1, prev + 1))}
                  className="flex items-center gap-1.5 px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold transition shadow-sm"
                >
                  <span>Câu tiếp theo</span>
                  <ArrowRight className="w-4 h-4" />
                </button>
              ) : (
                <button
                  onClick={handleSubmitExam}
                  className="flex items-center gap-1.5 px-6 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold transition shadow-md shadow-emerald-600/20"
                >
                  <CheckCircle2 className="w-4 h-4" />
                  <span>Hoàn tất & Nộp bài</span>
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    );
  }

  // =========================================================================
  // VIEW 4: DETAILED EXAM SCORE REPORT & EXPLANATION (KẾT QUẢ & GIẢI CHI TIẾT)
  // =========================================================================
  if (viewMode === 'result' && activeTest) {
    const { correctCount, totalCount, percentage, scaledScore } = calculateResults();

    return (
      <div className="max-w-5xl mx-auto px-4 sm:px-6 py-8 space-y-8 animate-in fade-in duration-300">
        {/* Toast feedback for saving vocab */}
        {savedVocabFeedback && (
          <div className="fixed top-20 right-5 z-50 p-3 rounded-xl bg-emerald-600 text-white text-xs font-bold shadow-xl animate-in slide-in-from-right duration-200">
            {savedVocabFeedback}
          </div>
        )}

        {/* Score Summary Card */}
        <div
          className={`p-6 sm:p-8 rounded-3xl border shadow-xl relative overflow-hidden ${
            isDarkMode
              ? 'bg-gradient-to-br from-slate-900 via-indigo-950/40 to-slate-900 border-indigo-900/50'
              : 'bg-gradient-to-br from-indigo-50 via-white to-sky-50 border-indigo-100'
          }`}
        >
          <div className="flex flex-col sm:flex-row items-center justify-between gap-6">
            <div>
              <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold bg-indigo-600 text-white mb-2">
                <Award className="w-3.5 h-3.5" />
                <span>Báo Cáo Điểm Chuẩn ETS / Cambridge</span>
              </div>
              <h2 className="text-2xl sm:text-3xl font-black">{activeTest.title}</h2>
              <p className="text-xs text-slate-500 mt-1">
                Kỳ thi: {activeTest.examType} &bull; {activeTest.part} &bull; Mục tiêu: {activeTest.targetLevel}
              </p>
            </div>

            <div className="flex items-center gap-6">
              <div className="text-center">
                <div className="text-3xl sm:text-4xl font-black text-indigo-600 dark:text-indigo-400">
                  {correctCount}/{totalCount}
                </div>
                <div className="text-[11px] font-bold text-slate-400 uppercase mt-0.5">Số câu đúng</div>
              </div>

              <div className="h-12 w-px bg-slate-200 dark:bg-slate-800" />

              <div className="text-center">
                <div className="text-3xl sm:text-4xl font-black text-emerald-600 dark:text-emerald-400">
                  {percentage}%
                </div>
                <div className="text-[11px] font-bold text-slate-400 uppercase mt-0.5">Tỉ lệ chính xác</div>
              </div>

              <div className="h-12 w-px bg-slate-200 dark:bg-slate-800" />

              <div className="text-center">
                <div className="text-base sm:text-lg font-black text-rose-600 dark:text-rose-400">
                  {scaledScore}
                </div>
                <div className="text-[11px] font-bold text-slate-400 uppercase mt-0.5">Điểm quy đổi</div>
              </div>
            </div>
          </div>

          <div className="mt-6 pt-6 border-t border-slate-200 dark:border-slate-800 flex flex-wrap gap-3">
            <button
              onClick={() => handleStartTest(activeTest)}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs transition shadow-sm"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              <span>Làm Lại Đề Này</span>
            </button>
            <button
              onClick={() => setViewMode('create')}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl border text-xs font-bold transition hover:bg-slate-100 dark:hover:bg-slate-800"
            >
              <Sparkles className="w-3.5 h-3.5 text-amber-500" />
              <span>Tạo Đề Mới Cùng Dạng Bằng AI</span>
            </button>
            <button
              onClick={() => setViewMode('library')}
              className="px-5 py-2.5 rounded-xl text-xs font-bold text-slate-500 hover:text-slate-800 transition"
            >
              Về Thư Viện Đề
            </button>
          </div>
        </div>

        {/* Detailed Answer Key & Pedagogical Explanations */}
        <div className="space-y-6">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-extrabold flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-emerald-500" />
              <span>Đáp Án Chi Tiết, Dịch Nghĩa & Phân Tích Bẫy Đề Thi</span>
            </h3>
            <span className="text-xs text-slate-400">
              Nhấp nút Bookmark để lưu từ vựng đắt giá vào Sổ tay
            </span>
          </div>

          {activeTest.questions.map((q, idx) => {
            const userAns = userAnswers[q.id]?.toUpperCase();
            const correctAns = q.correctAnswer.toUpperCase();
            const isCorrect = userAns === correctAns;

            return (
              <div
                key={q.id}
                className={`p-6 rounded-3xl border transition-all ${
                  isCorrect
                    ? isDarkMode
                      ? 'bg-slate-900 border-emerald-900/40'
                      : 'bg-white border-emerald-200 shadow-xs'
                    : isDarkMode
                    ? 'bg-slate-900 border-rose-900/40'
                    : 'bg-white border-rose-200 shadow-xs'
                }`}
              >
                {/* Question Status Header */}
                <div className="flex items-center justify-between gap-3 pb-3 border-b border-slate-100 dark:border-slate-800">
                  <div className="flex items-center gap-2">
                    <span
                      className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold text-white ${
                        isCorrect ? 'bg-emerald-600' : 'bg-rose-600'
                      }`}
                    >
                      {idx + 1}
                    </span>
                    <span className="text-xs font-bold">
                      {isCorrect ? (
                        <span className="text-emerald-600 dark:text-emerald-400">Trả lời đúng</span>
                      ) : (
                        <span className="text-rose-600 dark:text-rose-400">
                          {userAns ? `Trả lời sai (Bạn chọn ${userAns})` : 'Chưa chọn đáp án'}
                        </span>
                      )}
                    </span>
                  </div>

                  <div className="text-xs font-bold px-3 py-1 rounded-lg bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-800">
                    Đáp án đúng: {correctAns}
                  </div>
                </div>

                {/* Question Prompt */}
                <div className="mt-4 font-bold text-sm sm:text-base leading-relaxed">
                  {q.question}
                </div>

                {/* Options Comparison */}
                <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {q.options.map((opt, oIdx) => {
                    const letter = opt.startsWith('(') ? opt.charAt(1) : String.fromCharCode(65 + oIdx);
                    const isUserChoice = userAns === letter;
                    const isRightOption = correctAns === letter;

                    return (
                      <div
                        key={opt}
                        className={`p-3 rounded-xl border text-xs flex items-center gap-2.5 ${
                          isRightOption
                            ? 'bg-emerald-50 dark:bg-emerald-950/60 border-emerald-300 text-emerald-800 dark:text-emerald-300 font-bold'
                            : isUserChoice && !isRightOption
                            ? 'bg-rose-50 dark:bg-rose-950/60 border-rose-300 text-rose-800 dark:text-rose-300 font-bold'
                            : 'border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-400'
                        }`}
                      >
                        <span
                          className={`w-5 h-5 rounded-md flex items-center justify-center text-[10px] font-bold ${
                            isRightOption
                              ? 'bg-emerald-600 text-white'
                              : isUserChoice
                              ? 'bg-rose-600 text-white'
                              : 'bg-slate-200 dark:bg-slate-700'
                          }`}
                        >
                          {letter}
                        </span>
                        <span>{opt}</span>
                      </div>
                    );
                  })}
                </div>

                {/* Detailed Pedagogical Explanation */}
                <div className="mt-4 p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700/80 space-y-2">
                  <div className="flex items-center gap-1.5 text-xs font-bold text-indigo-600 dark:text-indigo-400">
                    <Sparkles className="w-3.5 h-3.5" />
                    <span>Giải thích chi tiết & Bẫy đề thi:</span>
                  </div>
                  <p className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed whitespace-pre-line">
                    {q.explanation}
                  </p>

                  {q.translation && (
                    <div className="pt-2 border-t border-slate-200 dark:border-slate-700 text-xs text-slate-600 dark:text-slate-400">
                      <strong className="text-slate-700 dark:text-slate-300">Dịch nghĩa:</strong>{' '}
                      {q.translation}
                    </div>
                  )}
                </div>

                {/* Key Vocabulary in Question */}
                {q.keyVocab && q.keyVocab.length > 0 && (
                  <div className="mt-4 pt-3 border-t border-slate-100 dark:border-slate-800">
                    <span className="text-[11px] font-bold text-slate-400 block mb-2">
                      Từ vựng ăn điểm trong câu hỏi:
                    </span>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                      {q.keyVocab.map((v) => (
                        <div
                          key={v.word}
                          className="flex items-center justify-between p-2.5 rounded-xl border border-slate-200 dark:border-slate-800 text-xs bg-white dark:bg-slate-900"
                        >
                          <div className="min-w-0 pr-2">
                            <div className="font-bold flex items-center gap-1.5">
                              <span className="text-indigo-600 dark:text-indigo-400">{v.word}</span>
                              <span className="text-[10px] text-slate-400 italic">({v.pos})</span>
                              <span className="text-[11px] font-mono text-slate-500">{v.phonetic}</span>
                            </div>
                            <div className="text-[11px] text-slate-600 dark:text-slate-400 truncate">
                              {v.meaning}
                            </div>
                          </div>

                          <div className="flex items-center gap-1">
                            <button
                              onClick={() => speak(v.word, 'en')}
                              className="p-1.5 rounded-lg text-slate-400 hover:text-indigo-600 hover:bg-slate-100 dark:hover:bg-slate-800 transition"
                              title="Nghe phát âm"
                            >
                              <Volume2 className="w-3.5 h-3.5" />
                            </button>
                            <button
                              onClick={() => handleSaveVocabToNotebook(v.word, v.meaning, v.phonetic)}
                              className="p-1.5 rounded-lg text-slate-400 hover:text-amber-500 hover:bg-amber-50 dark:hover:bg-amber-950/60 transition"
                              title="Lưu từ này vào Sổ từ vựng"
                            >
                              <Bookmark className="w-3.5 h-3.5" />
                            </button>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    );
  }

  return null;
};
