# -*- coding: utf-8 -*-
# Oxford 3000 / 5000 & CEFR Standard English Vocabulary Dataset (>700 words)

ENGLISH_A1 = [
    # Unit 1: Greetings & Daily Life
    ("Greet", "/ɡriːt/", "verb", "chào hỏi, chào đón", "She greeted the guests with a warm smile.", "Cô ấy chào đón các vị khách bằng nụ cười ấm áp.", ["greet warmly"], "G-R-E-E-T -> khi gặp thì cất tiếng chào."),
    ("Introduce", "/ˌɪn.trəˈdjuːs/", "verb", "giới thiệu, làm quen", "Let me introduce my best friend to you.", "Để tôi giới thiệu người bạn thân nhất của tôi với bạn.", ["introduce oneself"], "Intro = mở đầu, bước vào làm quen."),
    ("Welcome", "/ˈwel.kəm/", "verb", "chào mừng, hoan nghênh", "Welcome to our English learning platform!", "Chào mừng bạn đến với nền tảng học tiếng Anh của chúng tôi!", ["warm welcome"], "Well + come = đến một cách tốt đẹp."),
    ("Name", "/neɪm/", "noun", "tên gọi, danh xưng", "What is your full name?", "Tên đầy đủ của bạn là gì?", ["first name", "family name"], "Từ cơ bản nhất khi bắt đầu giao tiếp."),
    ("Age", "/eɪdʒ/", "noun", "tuổi tác, độ tuổi", "Children under the age of five travel free.", "Trẻ em dưới năm tuổi được đi lại miễn phí.", ["at the age of"], "Hỏi tuổi: What is your age?"),
    ("Live", "/lɪv/", "verb", "sống, cư ngụ", "I live in a peaceful neighborhood in Hanoi.", "Tôi sống tại một khu phố yên bình ở Hà Nội.", ["live in a city"], "Phân biệt live /lɪv/ (động từ) và life /laɪf/ (danh từ)."),
    ("Country", "/ˈkʌn.tri/", "noun", "quốc gia, đất nước", "Vietnam is a beautiful and hospitable country.", "Việt Nam là một đất nước tươi đẹp và hiếu khách.", ["foreign country"], "Country còn có nghĩa là vùng thôn quê."),
    ("Nationality", "/ˌnæʃ.ənˈæl.ə.ti/", "noun", "quốc tịch", "She holds dual nationality.", "Cô ấy mang hai quốc tịch.", ["dual nationality"], "Gốc từ nation (quốc gia) + đuôi ality."),
    ("Language", "/ˈlæŋ.ɡwɪdʒ/", "noun", "ngôn ngữ, tiếng nói", "English is a global language.", "Tiếng Anh là một ngôn ngữ toàn cầu.", ["native language", "foreign language"], "Âm /ɡwɪdʒ/ phát âm tròn môi."),
    ("Friend", "/frend/", "noun", "người bạn", "A true friend is always by your side.", "Một người bạn chân chính luôn ở bên cạnh bạn.", ["close friend", "best friend"], "Âm e ngắn, đừng phát âm nhầm thành fri-end."),
    ("Meet", "/miːt/", "verb", "gặp gỡ, hẹn gặp", "Nice to meet you in person.", "Rất vui được gặp bạn trực tiếp.", ["meet someone"], "Âm /iː/ kéo dài."),
    ("Address", "/əˈdres/", "noun", "địa chỉ liên lạc", "Please write your residential address here.", "Vui lòng viết địa chỉ cư trú của bạn vào đây.", ["home address", "email address"], "Trọng âm nhấn vào âm thứ hai /dres/."),
    ("Phone", "/fəʊn/", "noun", "điện thoại", "My phone is ringing in the living room.", "Điện thoại của tôi đang đổ chuông trong phòng khách.", ["phone number"], "Ph phát âm là /f/."),
    ("Email", "/ˈiː.meɪl/", "noun", "thư điện tử", "I will send the study guide by email.", "Tôi sẽ gửi tài liệu học tập qua email.", ["send an email"], "Electronic + mail."),
    ("Spell", "/spel/", "verb", "đánh vần", "How do you spell your last name?", "Bạn đánh vần họ của mình như thế nào?", ["spell correctly"], "Cần dùng khi xác nhận họ tên tiếng nước ngoài."),
    ("Person", "/ˈpɜː.sən/", "noun", "người, cá nhân", "She is a very kind and thoughtful person.", "Cô ấy là một người rất tốt bụng và chu đáo.", ["in person"], "Số nhiều thông thường là people."),
    ("People", "/ˈpiː.pəl/", "noun", "con người, mọi người", "Many people enjoy traveling during holidays.", "Nhiều người thích đi du lịch trong kỳ nghỉ.", ["young people"], "Danh từ số nhiều chỉ tập hợp người."),
    ("Woman", "/ˈwʊm.ən/", "noun", "người phụ nữ", "She is an inspiring and strong woman.", "Cô ấy là một người phụ nữ mạnh mẽ và truyền cảm hứng.", ["working woman"], "Số nhiều viết là women /ˈwɪm.ɪn/."),
    ("Man", "/mæn/", "noun", "người đàn ông", "He is a hard-working and honest man.", "Anh ấy là một người đàn ông chăm chỉ và trung thực.", ["young man"], "Số nhiều viết là men /men/."),
    ("Boy", "/bɔɪ/", "noun", "cậu bé, bé trai", "The young boy is reading a comic book.", "Cậu bé đang đọc một cuốn truyện tranh.", ["school boy"], "Nguyên âm đôi /ɔɪ/."),
    ("Girl", "/ɡɜːl/", "noun", "cô bé, bé gái", "The girl smiled happily at her teacher.", "Bé gái mỉm cười hạnh phúc với cô giáo.", ["little girl"], "Âm /ɜː/ dài kết hợp đưa lưỡi âm /l/."),
    ("Baby", "/ˈbeɪ.bi/", "noun", "em bé sơ sinh", "The baby is sleeping peacefully in the crib.", "Em bé đang ngủ say sưa trong nôi.", ["newborn baby"], "Trọng âm âm tiết thứ nhất."),
    ("Family", "/ˈfæm.əl.i/", "noun", "gia đình", "Family is the foundation of our happiness.", "Gia đình là nền tảng của hạnh phúc chúng ta.", ["happy family"], "Trọng âm âm tiết đầu /ˈfæm/."),
    ("Parent", "/ˈpeə.rənt/", "noun", "bố hoặc mẹ, phụ huynh", "Parents love their children unconditionally.", "Cha mẹ yêu thương con cái vô điều kiện.", ["both parents"], "Số nhiều parents chỉ cả cha lẫn mẹ."),
    ("Mother", "/ˈmʌð.ər/", "noun", "mẹ, thân mẫu", "My mother makes the best chicken soup.", "Mẹ tôi nấu món súp gà ngon nhất.", ["mother tongue"], "Âm /ð/ kẹp đầu lưỡi giữa hai hàm răng."),
    ("Father", "/ˈfɑː.ðər/", "noun", "bố, người cha", "His father teaches history at school.", "Bố của anh ấy dạy môn lịch sử ở trường.", ["like father like son"], "Nguyên âm /ɑː/ dài và trầm."),
    ("Sister", "/ˈsɪs.tər/", "noun", "chị gái, em gái", "My older sister is a nurse at the hospital.", "Chị gái tôi là y tá tại bệnh viện.", ["older sister", "younger sister"], "Dùng older/younger để phân biệt lớn/nhỏ."),
    ("Brother", "/ˈbrʌð.ər/", "noun", "anh trai, em trai", "He plays football with his brother every Sunday.", "Anh ấy chơi bóng đá với anh trai mỗi chủ nhật.", ["older brother", "twin brother"], "Âm /ð/ ở giữa từ."),
    ("Daughter", "/ˈdɔː.tər/", "noun", "con gái", "Their daughter is studying medicine.", "Con gái họ đang học ngành y khoa.", ["only daughter"], "Chữ gh câm, phát âm /dɔː.tər/."),
    ("Son", "/sʌn/", "noun", "con trai", "Their son is very talented at mathematics.", "Con trai họ rất có năng khiếu toán học.", ["eldest son"], "Đồng âm với sun (mặt trời)."),

    # Unit 2: Home & Daily Objects
    ("House", "/haʊs/", "noun", "ngôi nhà", "They bought a cozy house with a green garden.", "Họ đã mua một ngôi nhà ấm cúng có khu vườn xanh mát.", ["in the house"], "Động từ phát âm /haʊz/, danh từ phát âm /haʊs/."),
    ("Home", "/həʊm/", "noun", "mái ấm, tổ ấm", "There is no place like home.", "Không nơi nào tuyệt vời bằng mái ấm gia đình.", ["at home", "feel at home"], "Home gợi cảm giác ấm áp hơn house."),
    ("Room", "/ruːm/", "noun", "căn phòng", "This room gets plenty of natural sunlight.", "Căn phòng này đón rất nhiều ánh sáng tự nhiên.", ["living room", "hotel room"], "Nguyên âm /uː/ dài."),
    ("Kitchen", "/ˈkɪtʃ.ən/", "noun", "nhà bếp", "Mom is preparing dinner in the kitchen.", "Mẹ đang chuẩn bị bữa tối trong bếp.", ["modern kitchen"], "Âm /tʃ/ bật hơi dứt khoát."),
    ("Bedroom", "/ˈbed.ruːm/", "noun", "phòng ngủ", "Keep your bedroom quiet and dark for good sleep.", "Giữ phòng ngủ yên tĩnh và tối để có giấc ngủ ngon.", ["master bedroom"], "Bed (giường) + room (phòng)."),
    ("Bathroom", "/ˈbɑːθ.ruːm/", "noun", "phòng tắm", "The bathroom is clean and well-ventilated.", "Phòng tắm rất sạch sẽ và thông thoáng.", ["private bathroom"], "Bath (tắm) + room."),
    ("Living room", "/ˈlɪv.ɪŋ ˌruːm/", "noun", "phòng khách", "We gathered in the living room to watch a movie.", "Chúng tôi quây quần ở phòng khách để xem phim.", ["cozy living room"], "Nơi sinh hoạt chung của gia đình."),
    ("Door", "/dɔːr/", "noun", "cửa ra vào", "Please close the door gently.", "Vui lòng đóng cửa nhẹ nhàng.", ["front door", "open the door"], "Âm /ɔː/ dài."),
    ("Window", "/ˈwɪn.dəʊ/", "noun", "cửa sổ", "Open the window to let fresh air inside.", "Mở cửa sổ để đón không khí trong lành vào.", ["look out of the window"], "Âm kết thúc /dəʊ/."),
    ("Table", "/ˈteɪ.bəl/", "noun", "cái bàn", "We sat around the table for lunch.", "Chúng tôi ngồi quanh bàn ăn bữa trưa.", ["dining table"], "On the table (đang được thảo luận)."),
    ("Chair", "/tʃeər/", "noun", "cái ghế", "Take a comfortable chair and relax.", "Hãy chọn một chiếc ghế thoải mái và thư giãn.", ["wooden chair"], "Âm /tʃ/ đầu từ."),
    ("Bed", "/bed/", "noun", "chiếc giường", "A comfortable bed ensures restful sleep.", "Một chiếc giường êm ái đảm bảo giấc ngủ thư thái.", ["go to bed"], "Go to bed (đi ngủ)."),
    ("Clock", "/klɒk/", "noun", "đồng hồ treo tường", "The wall clock struck midnight.", "Chiếc đồng hồ treo tường điểm nửa đêm.", ["alarm clock"], "Clock (đồng hồ bàn/tường), watch (đồng hồ đeo tay)."),
    ("Lamp", "/læmp/", "noun", "đèn bàn, đèn chiếu", "Turn on the desk lamp when you read.", "Bật đèn bàn lên khi bạn đọc sách.", ["desk lamp", "reading lamp"], "Bật đèn: turn on the lamp."),
    ("Key", "/kiː/", "noun", "chìa khóa, điều then chốt", "Hard work is the key to achieving your goals.", "Chăm chỉ là chìa khóa để đạt được mục tiêu của bạn.", ["car key", "key factor"], "Âm /iː/ kéo dài."),

    # Unit 3: Daily Routine & Time
    ("Time", "/taɪm/", "noun", "thời gian, thời điểm", "Time management is an essential life skill.", "Quản lý thời gian là kỹ năng sống thiết yếu.", ["on time", "in time"], "On time (đúng giờ), in time (kịp giờ)."),
    ("Day", "/deɪ/", "noun", "ngày, ban ngày", "Have a wonderful and productive day!", "Chúc bạn một ngày tuyệt vời và hiệu quả!", ["every day", "day off"], "Every day (viết rời) là phó từ, everyday (viết liền) là tính từ."),
    ("Week", "/wiːk/", "noun", "tuần lễ", "I will finish this vocabulary course in a week.", "Tôi sẽ hoàn thành khóa từ vựng này trong một tuần.", ["weekend", "this week"], "Âm /iː/ dài."),
    ("Month", "/mʌnθ/", "noun", "tháng", "We have an important exam next month.", "Chúng tôi có một kỳ thi quan trọng vào tháng tới.", ["last month", "next month"], "Âm /θ/ đặt lưỡi giữa hai răng."),
    ("Year", "/jɪər/", "noun", "năm", "Happy New Year to you and your loved ones!", "Chúc bạn và những người thân yêu một năm mới hạnh phúc!", ["calendar year"], "Âm /j/ nhẹ đầu từ."),
    ("Today", "/təˈdeɪ/", "noun", "hôm nay", "Today is the best day to start a good habit.", "Hôm nay là ngày tốt nhất để bắt đầu một thói quen tốt.", ["today's news"], "Nhấn âm thứ hai /deɪ/."),
    ("Tomorrow", "/təˈmɒr.əʊ/", "noun", "ngày mai", "Tomorrow holds endless new possibilities.", "Ngày mai mang theo vô vàn cơ hội mới.", ["tomorrow morning"], "Trọng âm rơi vào âm tiết thứ hai /mɒr/."),
    ("Yesterday", "/ˈjes.tə.deɪ/", "noun", "hôm qua", "Yesterday is history, today is a gift.", "Hôm qua đã là quá khứ, hôm nay là một món quà.", ["yesterday afternoon"], "Nhấn âm thứ nhất /ˈjes/."),
    ("Morning", "/ˈmɔː.nɪŋ/", "noun", "buổi sáng", "Morning exercise boosts your energy levels.", "Tập thể dục buổi sáng giúp tăng mức năng lượng của bạn.", ["early morning"], "Good morning!"),
    ("Afternoon", "/ˌɑːf.təˈnuːn/", "noun", "buổi chiều", "Let us have coffee together this afternoon.", "Chiều nay chúng ta cùng đi uống cà phê nhé.", ["in the afternoon"], "Trọng âm rơi vào âm tiết cuối /nuːn/."),
    ("Evening", "/ˈiːv.nɪŋ/", "noun", "buổi tối", "The city looks gorgeous in the evening.", "Thành phố trông tuyệt đẹp vào buổi tối.", ["in the evening"], "Phát âm hai âm tiết /ˈiːv.nɪŋ/."),
    ("Night", "/naɪt/", "noun", "ban đêm", "Have a good night and sweet dreams.", "Chúc bạn một đêm ngon giấc và có những giấc mơ đẹp.", ["at night"], "Luôn đi với at: at night."),
    ("Hour", "/aʊər/", "noun", "giờ, tiếng đồng hồ", "The flight takes approximately two hours.", "Chuyến bay mất khoảng hai tiếng đồng hồ.", ["an hour ago"], "Chữ h câm, dùng mạo từ an hour."),
    ("Minute", "/ˈmɪn.ɪt/", "noun", "phút", "Please wait a minute, I will be right there.", "Xin vui lòng đợi một phút, tôi sẽ tới ngay.", ["in a minute"], "Nhấn âm thứ nhất /ˈmɪn/."),
    ("Second", "/ˈsek.ənd/", "noun", "giây (thời gian)", "Every second counts in an emergency.", "Từng giây phút đều quý giá trong tình huống khẩn cấp.", ["just a second"], "Second còn có nghĩa là thứ nhì."),

    # Unit 4: Food & Drink
    ("Food", "/fuːd/", "noun", "thực phẩm, đồ ăn", "Healthy food gives you strength and vitality.", "Thức ăn lành mạnh mang lại cho bạn sức mạnh và sinh lực.", ["healthy food", "fast food"], "Nguyên âm /uː/ dài."),
    ("Water", "/ˈwɔː.tər/", "noun", "nước uống", "Drink at least two liters of water daily.", "Hãy uống ít nhất hai lít nước mỗi ngày.", ["mineral water", "tap water"], "Nhu cầu không thể thiếu cho cơ thể."),
    ("Bread", "/bred/", "noun", "bánh mì", "He toasted two slices of bread for breakfast.", "Anh ấy đã nướng hai lát bánh mì cho bữa sáng.", ["a slice of bread"], "Ea phát âm là /e/ ngắn."),
    ("Rice", "/raɪs/", "noun", "cơm, gạo", "Steamed rice is served with every Asian meal.", "Cơm trắng được dọn kèm trong mọi bữa ăn châu Á.", ["steamed rice", "fried rice"], "Phát âm /raɪs/ với âm /s/ rõ."),
    ("Meat", "/miːt/", "noun", "thịt", "Lean meat provides high quality protein.", "Thịt nạc cung cấp lượng đạm chất lượng cao.", ["fresh meat"], "Đồng âm với meet (gặp)."),
    ("Fish", "/fɪʃ/", "noun", "cá", "Salmon is a very nutritious fish.", "Cá hồi là một loại cá rất giàu dinh dưỡng.", ["grilled fish"], "Số nhiều vẫn giữ nguyên là fish."),
    ("Fruit", "/fruːt/", "noun", "trái cây, hoa quả", "Fresh seasonal fruit is packed with vitamins.", "Trái cây tươi theo mùa chứa rất nhiều vitamin.", ["fresh fruit"], "Chữ i câm, phát âm /fruːt/."),
    ("Vegetable", "/ˈvedʒ.tə.bəl/", "noun", "rau củ", "Green vegetables help digestion.", "Rau xanh giúp ích cho hệ tiêu hóa.", ["fresh vegetables"], "Phát âm ba âm tiết: /ˈvedʒ.tə.bəl/."),
    ("Egg", "/eɡ/", "noun", "quả trứng", "Boiled eggs are easy to prepare.", "Trứng luộc rất dễ chuẩn bị.", ["boiled egg", "fried egg"], "Nguồn protein phổ biến."),
    ("Milk", "/mɪlk/", "noun", "sữa tươi", "Children drink milk to build strong bones.", "Trẻ em uống sữa để giúp xương chắc khỏe.", ["fresh milk", "whole milk"], "Âm kết thúc /lk/."),
    ("Coffee", "/ˈkɒf.i/", "noun", "cà phê", "A morning coffee helps sharpen your focus.", "Một ly cà phê sáng giúp tăng độ tập trung của bạn.", ["cup of coffee"], "Nhấn âm thứ nhất /ˈkɒf/."),
    ("Tea", "/tiː/", "noun", "trà, chè", "Herbal tea helps you relax before bed.", "Trà thảo mộc giúp bạn thư giãn trước khi ngủ.", ["green tea", "black tea"], "Văn hóa thưởng trà truyền thống."),
    ("Sugar", "/ˈʃʊɡ.ər/", "noun", "đường cát", "Limit your sugar intake to stay healthy.", "Hạn chế lượng đường nạp vào để giữ sức khỏe tốt.", ["brown sugar"], "Bắt đầu bằng âm /ʃ/ dù viết là s."),
    ("Salt", "/sɒlt/", "noun", "muối ăn", "A small amount of salt enhances the taste.", "Một chút muối sẽ làm tăng hương vị món ăn.", ["sea salt"], "Âm /ɒ/ tròn môi."),
    ("Soup", "/suːp/", "noun", "canh, món súp", "Warm chicken soup is comforting when you are sick.", "Món súp gà ấm áp rất dễ chịu khi bạn bị ốm.", ["hot soup"], "Nguyên âm /uː/ dài."),

    # Unit 5: Common Actions
    ("Eat", "/iːt/", "verb", "ăn uống", "Eat slowly and chew your food thoroughly.", "Hãy ăn chậm và nhai kỹ thức ăn của bạn.", ["eat well"], "Quá khứ: ate /eɪt/, phân từ: eaten /ˈiː.tən/."),
    ("Drink", "/drɪŋk/", "verb", "uống", "Remember to drink enough fluids after exercising.", "Nhớ uống đủ nước sau khi tập thể dục.", ["drink water"], "Quá khứ: drank, phân từ: drunk."),
    ("Sleep", "/sliːp/", "verb", "ngủ", "Getting adequate sleep keeps your mind sharp.", "Ngủ đủ giấc giúp tâm trí bạn luôn minh mẫn.", ["sleep soundly"], "Quá khứ & phân từ: slept."),
    ("Wake", "/weɪk/", "verb", "thức giấc", "I wake up naturally at sunrise.", "Tôi thức giấc tự nhiên vào lúc bình minh.", ["wake up early"], "Wake up (tỉnh giấc)."),
    ("Walk", "/wɔːk/", "verb", "đi bộ", "We walk through the park every afternoon.", "Chúng tôi đi bộ qua công viên mỗi buổi chiều.", ["go for a walk"], "Chữ l câm, phát âm /wɔːk/."),
    ("Run", "/rʌn/", "verb", "chạy nhanh", "He runs regularly to maintain stamina.", "Anh ấy chạy bộ đều đặn để duy trì thể lực.", ["run fast"], "Quá khứ: ran, phân từ: run."),
    ("See", "/siː/", "verb", "trông thấy, nhìn nhận", "I can see the ocean from my hotel window.", "Tôi có thể nhìn thấy đại dương từ cửa sổ khách sạn.", ["see clearly"], "Chỉ khả năng thị giác tự nhiên."),
    ("Look", "/lʊk/", "verb", "nhìn ngắm, quan sát", "Look at the colorful butterflies in the garden.", "Hãy nhìn những chú bướm đầy màu sắc trong vườn kìa.", ["look at", "look forward to"], "Look at (chủ động hướng mắt nhìn)."),
    ("Watch", "/wɒtʃ/", "verb", "theo dõi, xem", "We love watching wildlife documentaries.", "Chúng tôi thích xem phim tài liệu về thế giới hoang dã.", ["watch television"], "Xem một chuyển động (watch a match/movie)."),
    ("Hear", "/hɪər/", "verb", "nghe thấy", "Can you hear the birds singing outside?", "Bạn có nghe thấy tiếng chim hót bên ngoài không?", ["hear a sound"], "Khả năng nghe tự nhiên của tai."),
    ("Listen", "/ˈlɪs.ən/", "verb", "chăm chú lắng nghe", "Listen actively to understand others better.", "Hãy chủ động lắng nghe để thấu hiểu người khác hơn.", ["listen carefully", "listen to music"], "Chữ t câm, luôn đi với giới từ to."),
    ("Speak", "/spiːk/", "verb", "nói năng, phát biểu", "She speaks three languages fluently.", "Cô ấy nói được ba thứ tiếng một cách lưu loát.", ["speak clearly", "speak English"], "Speak + ngôn ngữ."),
    ("Talk", "/tɔːk/", "verb", "trò chuyện, đàm đạo", "We sat together and talked for hours.", "Chúng tôi ngồi bên nhau và trò chuyện suốt nhiều giờ.", ["talk with someone", "talk about"], "Chữ l câm, phát âm /tɔːk/."),
    ("Read", "/riːd/", "verb", "đọc sách", "Reading develops your imagination.", "Đọc sách giúp phát triển trí tưởng tượng của bạn.", ["read books"], "Hiện tại /riːd/, quá khứ /red/."),
    ("Write", "/raɪt/", "verb", "viết chữ, sáng tác", "Write your thoughts down in a personal journal.", "Hãy viết những suy nghĩ của bạn vào một cuốn nhật ký cá nhân.", ["write down"], "Chữ w câm, phát âm /raɪt/."),

    # Unit 6: Essential Adjectives & Qualities
    ("Big", "/bɪɡ/", "adj", "to lớn, vĩ đại", "They live in a big house by the lake.", "Họ sống trong một ngôi nhà lớn bên hồ.", ["big city", "big challenge"], "Trái nghĩa với small."),
    ("Small", "/smɔːl/", "adj", "nhỏ nhắn, khiêm tốn", "Small daily improvements yield massive results.", "Những cải thiện nhỏ hằng ngày đem lại kết quả to lớn.", ["small town", "small business"], "Trái nghĩa với big/large."),
    ("Good", "/ɡʊd/", "adj", "tốt đẹp, hay, giỏi", "Eating well and exercising is good for your health.", "Ăn uống điều độ và tập thể dục rất tốt cho sức khỏe của bạn.", ["good at", "good for"], "So sánh hơn: better, hơn nhất: best."),
    ("Bad", "/bæd/", "adj", "xấu, tồi tệ", "Bad habits are easy to form but hard to break.", "Thói quen xấu rất dễ hình thành nhưng khó từ bỏ.", ["bad news", "bad mood"], "So sánh hơn: worse, hơn nhất: worst."),
    ("Happy", "/ˈhæp.i/", "adj", "hạnh phúc, vui sướng", "A positive mindset creates a happy life.", "Một tư duy tích cực tạo nên một cuộc sống hạnh phúc.", ["feel happy", "happy with"], "Danh từ là happiness."),
    ("Sad", "/sæd/", "adj", "buồn bã, ủ rũ", "Music can comfort you when you feel sad.", "Âm nhạc có thể an ủi bạn khi bạn cảm thấy buồn.", ["feel sad", "sad story"], "Trái nghĩa với happy."),
    ("New", "/njuː/", "adj", "mới mẻ, vừa xuất hiện", "Every day is a chance for a new beginning.", "Mỗi ngày là một cơ hội cho một khởi đầu mới.", ["brand new", "new experience"], "Trái nghĩa với old."),
    ("Old", "/əʊld/", "adj", "cũ kỹ, già nua, lâu năm", "He cherishes memories with his old friends.", "Anh ấy nâng niu những kỷ niệm bên những người bạn lâu năm.", ["old friend", "old building"], "Trái nghĩa với new/young."),
    ("Young", "/jʌŋ/", "adj", "trẻ tuổi, thanh xuân", "Young minds are curious and eager to learn.", "Những tâm hồn trẻ tuổi luôn tò mò và khao khát học hỏi.", ["young generation"], "Trái nghĩa với old."),
    ("Hot", "/hɒt/", "adj", "nóng bức, cay nóng", "Take care when drinking hot tea.", "Hãy cẩn thận khi uống trà nóng.", ["hot weather", "hot water"], "Trái nghĩa với cold."),
    ("Cold", "/kəʊld/", "adj", "lạnh giá, buốt", "A cold shower invigorates your body in the morning.", "Tắm nước mát tiếp thêm sinh lực cho cơ thể bạn vào buổi sáng.", ["cold wind", "freezing cold"], "Catch a cold (bị cảm lạnh)."),
    ("Warm", "/wɔːm/", "adj", "ấm áp, nồng hậu", "They gave us a very warm and sincere welcome.", "Họ đã dành cho chúng tôi một sự đón tiếp vô cùng nồng hậu và chân thành.", ["warm weather", "warm heart"], "Cảm giác dễ chịu giữa lạnh và nóng."),
    ("Cool", "/kuːl/", "adj", "mát mẻ, điềm tĩnh, sành điệu", "A cool breeze swept across the lake.", "Một cơn gió mát lành thổi lướt qua mặt hồ.", ["cool weather", "stay cool"], "Stay cool (giữ bình tĩnh)."),
    ("Clean", "/kliːn/", "adj", "sạch sẽ, trong lành", "Clean air and water are fundamental rights.", "Không khí và nguồn nước sạch là những quyền cơ bản.", ["clean environment"], "Trái nghĩa với dirty."),
    ("Dirty", "/ˈdɜː.ti/", "adj", "dơ bẩn, chưa sạch", "Wash your dirty hands thoroughly before eating.", "Hãy rửa kỹ đôi bàn tay bẩn trước khi ăn.", ["dirty clothes"], "Trọng âm âm tiết đầu /ˈdɜː/."),

    # Unit 7: Places & Travel
    ("City", "/ˈsɪt.i/", "noun", "thành phố, đô thị", "The city center is vibrant and full of energy.", "Trung tâm thành phố rất sôi động và tràn đầy năng lượng.", ["big city", "city life"], "Số nhiều đổi y thành ies: cities."),
    ("Town", "/taʊn/", "noun", "thị trấn, phố huyện", "She grew up in a charming seaside town.", "Cô ấy lớn lên ở một thị trấn ven biển quyến rũ.", ["small town", "in town"], "Nhỏ hơn city, lớn hơn village."),
    ("Village", "/ˈvɪl.ɪdʒ/", "noun", "ngôi làng, vùng quê", "The peaceful mountain village attracts many visitors.", "Ngôi làng miền núi yên bình thu hút rất nhiều du khách.", ["peaceful village"], "Phát âm đuôi /ɪdʒ/."),
    ("Street", "/striːt/", "noun", "con đường, con phố", "Children were playing safely on the quiet street.", "Trẻ em đang chơi đùa an toàn trên con phố yên tĩnh.", ["main street", "cross the street"], "Đường phố trong đô thị."),
    ("Road", "/rəʊd/", "noun", "con đường bộ", "The winding mountain road offers spectacular views.", "Con đường núi uốn lượn mở ra những cảnh quan ngoạn mục.", ["country road", "on the road"], "Đường nối liền giữa các địa phương."),
    ("Park", "/pɑːk/", "noun", "công viên cây xanh", "Families enjoy picnics in the public park.", "Các gia đình thích đi dã ngoại trong công viên công cộng.", ["national park"], "Động từ park nghĩa là đỗ xe."),
    ("Shop", "/ʃɒp/", "noun", "cửa hàng, tiệm buôn", "There is a lovely book shop around the corner.", "Có một hiệu sách rất đáng yêu ở ngay góc phố.", ["gift shop", "book shop"], "Động từ shop nghĩa là đi mua sắm."),
    ("Market", "/ˈmɑː.kɪt/", "noun", "khu chợ, thị trường", "The local morning market sells fresh produce.", "Khu chợ sáng địa phương bán nông sản tươi sống.", ["flea market", "supermarket"], "Nhấn âm thứ nhất /ˈmɑː/."),
    ("School", "/skuːl/", "noun", "trường học", "Education at school shapes our future.", "Việc học tập ở trường định hình tương lai của chúng ta.", ["primary school", "high school"], "Ch phát âm là /k/."),
    ("Hospital", "/ˈhɒs.pɪ.təl/", "noun", "bệnh viện", "The city hospital has state-of-the-art medical equipment.", "Bệnh viện thành phố có trang thiết bị y tế tối tân.", ["general hospital"], "Nhấn âm đầu /ˈhɒs/."),
    ("Station", "/ˈsteɪ.ʃən/", "noun", "nhà ga, trạm dừng", "We will meet you at the central railway station.", "Chúng tôi sẽ đón bạn tại nhà ga xe lửa trung tâm.", ["bus station", "train station"], "Trọng âm âm tiết đầu /ˈsteɪ/."),
    ("Airport", "/ˈeə.pɔːt/", "noun", "sân bay, phi trường", "Arrive at the airport two hours before departure.", "Hãy đến sân bay hai tiếng trước giờ khởi hành.", ["international airport"], "Air (không khí) + port (cảng)."),
    ("Hotel", "/həʊˈtel/", "noun", "khách sạn", "We booked a comfortable room at a boutique hotel.", "Chúng tôi đã đặt một phòng tiện nghi tại khách sạn cổ điển.", ["five-star hotel"], "Trọng âm rơi vào âm tiết thứ hai /tel/."),
    ("Restaurant", "/ˈres.trɒnt/", "noun", "nhà hàng, quán ăn", "This family restaurant serves authentic Italian food.", "Nhà hàng gia đình này phục vụ các món Ý chính thống.", ["fancy restaurant"], "Thường phát âm 2 hoặc 3 âm tiết /ˈres.trɒnt/."),
    ("Bank", "/bæŋk/", "noun", "ngân hàng, bờ sông", "He deposited his savings into the commercial bank.", "Anh ấy đã gửi tiền tiết kiệm vào ngân hàng thương mại.", ["open a bank account"], "Bank còn có nghĩa là bờ sông (river bank)."),

    # Unit 8: School & Study Essentials
    ("Book", "/bʊk/", "noun", "cuốn sách", "A good book can change your perspective on life.", "Một cuốn sách hay có thể thay đổi cách nhìn của bạn về cuộc đời.", ["read a book", "textbook"], "Động từ book nghĩa là đặt trước."),
    ("Pen", "/pen/", "noun", "cây bút mực", "He signed the important contract with his gold pen.", "Anh ấy đã ký hợp đồng quan trọng bằng cây bút mạ vàng của mình.", ["ballpoint pen"], "Đồ dùng học tập quen thuộc."),
    ("Pencil", "/ˈpen.səl/", "noun", "cây bút chì", "Sketch the initial outline lightly with a pencil.", "Hãy phác thảo đường nét ban đầu nhẹ nhàng bằng bút chì.", ["colored pencil"], "Dễ dàng tẩy xóa khi cần."),
    ("Desk", "/desk/", "noun", "bàn học, bàn làm việc", "Keep your study desk uncluttered to focus better.", "Giữ bàn học gọn gàng để tập trung tốt hơn.", ["study desk", "office desk"], "Bàn chuyên dụng cho học tập/làm việc."),
    ("Bag", "/bæɡ/", "noun", "cặp sách, túi xách", "Pack your books and notebooks carefully into your bag.", "Hãy xếp sách và vở cẩn thận vào cặp của bạn.", ["school bag", "backpack"], "Vật dụng mang đồ hằng ngày."),
    ("Class", "/klɑːs/", "noun", "lớp học, tiết học", "The chemistry class begins at half past eight.", "Tiết học hóa học bắt đầu lúc tám giờ rưỡi.", ["attend class", "classmate"], "Classmate là bạn cùng lớp."),
    ("Lesson", "/ˈles.ən/", "noun", "bài học, kinh nghiệm", "Every failure teaches a valuable life lesson.", "Mỗi thất bại đều mang lại một bài học cuộc sống quý giá.", ["learn a lesson"], "Nhấn âm đầu /ˈles/."),
    ("Test", "/test/", "noun", "bài kiểm tra, thi cử", "Regular practice helps you ace any English test.", "Luyện tập thường xuyên giúp bạn đạt điểm tối đa trong mọi bài kiểm tra tiếng Anh.", ["take a test", "pass a test"], "Take a test (làm bài thi)."),
    ("Question", "/ˈkwes.tʃən/", "noun", "câu hỏi, thắc mắc", "Feel free to ask questions whenever you are confused.", "Cứ tự nhiên đặt câu hỏi bất cứ khi nào bạn thấy băn khoăn.", ["ask a question", "answer a question"], "Âm /tʃ/ ở giữa từ."),
    ("Answer", "/ˈɑːn.sər/", "noun", "câu trả lời, lời giải", "She found the correct answer after careful thought.", "Cô ấy đã tìm ra câu trả lời đúng sau khi suy nghĩ cẩn thận.", ["correct answer"], "Chữ w câm, phát âm /ˈɑːn.sər/."),
    ("Number", "/ˈnʌm.bər/", "noun", "con số, số lượng", "A large number of students attended the seminar.", "Một số lượng lớn sinh viên đã tham dự buổi hội thảo.", ["lucky number"], "A number of = một số."),
    ("Color", "/ˈkʌl.ər/", "noun", "màu sắc", "Bright colors stimulate creativity and energy.", "Những gam màu tươi sáng kích thích sự sáng tạo và năng lượng.", ["favorite color"], "Anh-Mỹ viết color, Anh-Anh viết colour."),
    ("Music", "/ˈmjuː.zɪk/", "noun", "âm nhạc", "Music connects people beyond borders.", "Âm nhạc kết nối con người vượt qua mọi biên giới.", ["listen to music"], "Nhấn âm thứ nhất /ˈmjuː/."),
    ("Game", "/ɡeɪm/", "noun", "trò chơi, ván đấu", "Learning vocabulary through educational games is fun.", "Học từ vựng qua các trò chơi giáo dục rất thú vị.", ["board game", "play a game"], "Vừa học vừa chơi tăng hiệu quả."),
    ("Picture", "/ˈpɪk.tʃər/", "noun", "bức tranh, bức ảnh", "A picture is worth a thousand words.", "Một bức tranh có giá trị bằng cả ngàn lời nói.", ["take a picture"], "Âm /tʃ/ ở âm tiết thứ hai.")
]

print(f"Total English A1 words: {len(ENGLISH_A1)}")
