# -*- coding: utf-8 -*-
import json

b1_b2_c1 = []

def add_e(lvl, unit, w, ph, pos, vn, ex, ex_vn, col, tip):
    b1_b2_c1.append({
        "id": f"en-{lvl.lower()}-{240 + len(b1_b2_c1) + 1:04d}",
        "language": "en",
        "level": lvl,
        "unit": unit,
        "word": w,
        "phonetic": ph,
        "partOfSpeech": pos,
        "vietnameseMeaning": vn,
        "example": ex,
        "exampleMeaning": ex_vn,
        "collocations": [col] if col else [],
        "mnemonicTip": tip
    })

# --- B1 (120 words) ---
b1_units = [
    ("Unit 1: Sự nghiệp & Thành tựu", [
        ("Accomplish", "/əˈkʌm.plɪʃ/", "động từ", "hoàn thành xuất sắc, đạt được", "With steady effort, you will accomplish great goals.", "Với nỗ lực kiên định, bạn sẽ hoàn thành những mục tiêu lớn lao.", "accomplish a mission", "Gốc từ complete -> hoàn thành mỹ mãn."),
        ("Efficient", "/ɪˈfɪʃ.ənt/", "tính từ", "hiệu suất cao, làm việc hiệu quả", "The automated workflow is remarkably efficient.", "Quy trình tự động hóa đạt hiệu suất làm việc rất cao.", "highly efficient", "Tối ưu hóa thời gian và công sức."),
        ("Challenge", "/ˈtʃæl.ɪndʒ/", "danh từ/động từ", "thách thức, thử thách cam go", "Embrace every difficult challenge as a teacher.", "Hãy đón nhận mọi thử thách cam go như một người thầy.", "face a challenge", "Thử thách tôi luyện bản lĩnh."),
        ("Opportunity", "/ˌɒp.əˈtʃuː.nə.ti/", "danh từ", "cơ hội, vận hội", "Preparation turns luck into real opportunity.", "Sự chuẩn bị kỹ càng biến vận may thành cơ hội thực sự.", "golden opportunity", "Thời cơ quý giá."),
        ("Achieve", "/əˈtʃiːv/", "động từ", "đạt được thành tựu", "Those who persevere achieve lasting success.", "Những ai kiên trì sẽ đạt được thành công bền vững.", "achieve goals", "Chạm tới mục tiêu."),
        ("Motivate", "/ˈməʊ.tɪ.veɪt/", "động từ", "thúc đẩy, tạo động lực", "Inspiring leaders motivate their entire team.", "Người lãnh đạo truyền cảm hứng tạo động lực cho cả đội ngũ.", "highly motivated", "Kích hoạt ý chí hành động."),
        ("Improve", "/ɪmˈpruːv/", "động từ", "cải thiện, tiến bộ", "Read daily to improve vocabulary retention.", "Đọc sách hàng ngày để cải thiện vốn từ vựng.", "improve skills", "Trở nên tốt hơn."),
        ("Develop", "/dɪˈvel.əp/", "động từ", "phát triển, hoàn thiện", "Engineers develop innovative software solutions.", "Các kỹ sư phát triển những giải pháp phần mềm đổi mới.", "develop a product", "Mở rộng và nâng tầm."),
        ("Manage", "/ˈmæn.ɪdʒ/", "động từ", "quản lý, thu xếp được", "Learn to manage personal finances prudently.", "Học cách quản lý tài chính cá nhân một cách thận trọng.", "manage time", "Điều hành kiểm soát."),
        ("Organize", "/ˈɔː.ɡən.aɪz/", "động từ", "tổ chức, sắp xếp khoa học", "Organize files cleanly to speed up productivity.", "Sắp xếp tệp tin gọn gàng để nâng cao năng suất.", "well organized", "Sắp đặt trật tự."),
        ("Productive", "/prəˈdʌk.tɪv/", "tính từ", "năng suất, sinh lời", "Morning hours are often the most productive.", "Những giờ buổi sáng thường là lúc làm việc năng suất nhất.", "productive day", "Tạo ra nhiều kết quả tốt."),
        ("Strategy", "/ˈstræt.ə.dʒi/", "danh từ", "chiến lược", "A clear strategy directs effective execution.", "Một chiến lược rõ ràng sẽ định hướng thực thi hiệu quả.", "business strategy", "Kế hoạch tổng thể dài hạn."),
        ("Target", "/ˈtɑː.ɡɪt/", "danh từ/động từ", "mục tiêu ngắm tới", "Hit quarterly targets through diligent execution.", "Đạt các mục tiêu hàng quý nhờ thực thi cần cù.", "reach the target", "Đích ngắm cụ thể."),
        ("Progress", "/ˈprəʊ.ɡres/", "danh từ/động từ", "tiến độ, sự tiến bộ", "Track daily learning progress to stay accountable.", "Theo dõi tiến độ học hàng ngày để tự nhắc nhở bản thân.", "make progress", "Sự đi lên từng ngày."),
        ("Success", "/səkˈses/", "danh từ", "thành công rực rỡ", "Patience and grit breed authentic success.", "Kiên nhẫn và lòng quả cảm tạo nên thành công đích thực.", "key to success", "Thành tựu viên mãn."),
        ("Collaborate", "/kəˈlæb.ə.reɪt/", "động từ", "hợp tác, phối hợp làm việc", "Researchers collaborate across global boundaries.", "Các nhà nghiên cứu hợp tác vượt qua ranh giới toàn cầu.", "collaborate closely", "Co (cùng) + Labor (lao động)."),
        ("Communicate", "/kəˈmjuː.nɪ.keɪt/", "động từ", "giao tiếp, truyền đạt", "Communicate complex concepts in simple terms.", "Truyền đạt những khái niệm phức tạp bằng từ ngữ giản dị.", "effective communication", "Trao đổi thông điệp."),
        ("Negotiate", "/nəˈɡəʊ.ʃi.eɪt/", "động từ", "đàm phán, thương lượng", "Negotiate win-win agreements with integrity.", "Đàm phán các thỏa thuận đôi bên cùng có lợi bằng sự chính trực.", "negotiate terms", "Thương lượng đi đến thống nhất."),
        ("Promote", "/prəˈməʊt/", "động từ", "thăng tiến, quảng bá", "Dedication earns you a deserved promotion.", "Sự tận hiến giúp bạn nhận được sự thăng chức xứng đáng.", "promote health", "Nâng lên vị thế cao hơn."),
        ("Responsible", "/rɪˈspɒn.sə.bəl/", "tính từ", "có tinh thần trách nhiệm", "Be responsible for your choices and habits.", "Hãy chịu trách nhiệm cho các lựa chọn và thói quen của bạn.", "take responsibility", "Gánh vác nghĩa vụ."),
        ("Reliable", "/rɪˈlaɪ.ə.bəl/", "tính từ", "đáng tin cậy", "She is a thoroughly reliable team member.", "Cô ấy là một thành viên đội ngũ hoàn toàn đáng tin cậy.", "reliable partner", "Có thể dựa cậy vào."),
        ("Professional", "/prəˈfeʃ.ən.əl/", "tính từ/danh từ", "chuyên nghiệp, giới chuyên gia", "Uphold high professional standards in writing.", "Duy trì tiêu chuẩn chuyên nghiệp cao trong văn phong.", "professional career", "Chuẩn mực nghề nghiệp."),
        ("Experience", "/ɪkˈspɪə.ri.əns/", "danh từ/động từ", "kinh nghiệm, trải nghiệm", "Valuable experience is forged through trials.", "Kinh nghiệm quý báu được tôi luyện qua thử thách.", "hands-on experience", "Vốn sống tích lũy."),
        ("Knowledge", "/ˈnɒl.ɪdʒ/", "danh từ", "tri thức, kiến thức", "Knowledge empowers lifelong freedom.", "Tri thức trao quyền tự do cho cả đời người.", "expand knowledge", "Âm 'k' câm: /ˈnɒl.ɪdʒ/."),
        ("Ability", "/əˈbɪl.ə.ti/", "danh từ", "năng lực, khả năng", "Foster your ability to solve novel problems.", "Bồi đắp năng lực giải quyết các vấn đề mới lạ.", "natural ability", "Khả năng làm được."),
        ("Expert", "/ˈek.spɜːt/", "danh từ/tính từ", "chuyên gia, tinh thông", "Consult an expert in data architecture.", "Hãy tham khảo ý kiến chuyên gia về kiến trúc dữ liệu.", "industry expert", "Bậc thầy một lĩnh vực."),
        ("Solution", "/səˈluː.ʃən/", "danh từ", "giải pháp, lời giải", "Engineers design elegant technical solutions.", "Các kỹ sư thiết kế những giải pháp kỹ thuật tinh tế.", "find a solution", "Tháo gỡ khúc mắc."),
        ("Decision", "/dɪˈsɪʒ.ən/", "danh từ", "quyết định", "Sound decisions require calm deliberation.", "Những quyết định đúng đắn đòi hỏi sự suy xét bình tĩnh.", "make a decision", "Lựa chọn dứt khoát."),
        ("Opinion", "/əˈpɪn.jən/", "danh từ", "quan điểm, ý kiến", "Respect differing opinions with an open mind.", "Tôn trọng những ý kiến khác biệt với tâm hồn cởi mở.", "in my opinion", "Cách nhìn nhận cá nhân."),
        ("Argument", "/ˈɑːɡ.jə.mənt/", "danh từ", "lập luận, sự tranh luận", "Construct a logical and compelling argument.", "Xây dựng một lập luận logic và thuyết phục.", "strong argument", "Lý lẽ minh chứng."),
    ]),
    ("Unit 2: Công nghệ, Xã hội & Đổi mới", [
        ("Revolutionize", "/ˌrev.əˈluː.ʃən.aɪz/", "động từ", "cách mạng hóa hoàn toàn", "AI will revolutionize diagnostic medicine.", "Trí tuệ nhân tạo sẽ cách mạng hóa y học chẩn đoán.", "revolutionize industry", "Biến đổi căn bản."),
        ("Environment", "/ɪnˈvaɪ.rən.mənt/", "danh từ", "môi trường sinh thái", "Preserve the natural environment for future youth.", "Gìn giữ môi trường tự nhiên cho thế hệ mai sau.", "protect environment", "Hệ sinh thái bao quanh."),
        ("Pollution", "/pəˈluː.ʃən/", "danh từ", "sự ô nhiễm", "Combat plastic pollution in rivers and oceans.", "Chống lại ô nhiễm rác thải nhựa ở sông và đại dương.", "air pollution", "Làm bẩn môi trường."),
        ("Recycle", "/ˌriːˈsaɪ.kəl/", "động từ", "tái chế", "Recycle aluminum cans to conserve energy.", "Tái chế lon nhôm để tiết kiệm năng lượng.", "recycle waste", "Biến phế liệu thành tài nguyên."),
        ("Energy", "/ˈen.ə.dʒi/", "danh từ", "năng lượng", "Solar energy is inexhaustible and clean.", "Năng lượng mặt trời là vô tận và sạch sẽ.", "renewable energy", "Nguồn phát động lực."),
        ("Resource", "/rɪˈzɔːs/", "danh từ", "nguồn tài nguyên", "Manage scarce water resources wisely.", "Quản lý nguồn tài nguyên nước khan hiếm một cách khôn ngoan.", "natural resources", "Tư liệu sản xuất và sống."),
        ("Protect", "/prəˈtekt/", "động từ", "bảo vệ, che chở", "Protect endangered biodiversity reserves.", "Bảo vệ các khu bảo tồn đa dạng sinh học quý hiếm.", "protect nature", "Giữ gìn an toàn."),
        ("Climate", "/ˈklaɪ.mət/", "danh từ", "khí hậu", "Global climate patterns are shifting rapidly.", "Các hình thái khí hậu toàn cầu đang biến đổi nhanh chóng.", "climate change", "Thời tiết theo chu kỳ năm."),
        ("Nature", "/ˈneɪ.tʃər/", "danh từ", "thiên nhiên", "Spending time in nature calms the heart.", "Dành thời gian giữa thiên nhiên làm lắng dịu con tim.", "mother nature", "Mẹ thiên nhiên."),
        ("Species", "/ˈspiː.ʃiːz/", "danh từ", "loài sinh vật", "Discover new marine species in deep trenches.", "Phát hiện những loài sinh vật biển mới ở rãnh biển sâu.", "endangered species", "Hình thái phân loại sinh học."),
        ("Technology", "/tekˈnɒl.ə.dʒi/", "danh từ", "công nghệ, kỹ thuật", "Modern technology bridges vast distances.", "Công nghệ hiện đại thu hẹp những khoảng cách xa xôi.", "advanced technology", "Ứng dụng khoa học."),
        ("Digital", "/ˈdɪdʒ.ɪ.təl/", "tính từ", "kỹ thuật số", "Digital tools streamline creative design.", "Các công cụ kỹ thuật số tối ưu hóa thiết kế sáng tạo.", "digital world", "Công nghệ số hóa."),
        ("Device", "/dɪˈvaɪs/", "danh từ", "thiết bị, công cụ", "Smart devices enhance household comfort.", "Thiết bị thông minh nâng tầm tiện nghi gia đình.", "electronic device", "Đồ dùng kỹ thuật."),
        ("Network", "/ˈnet.wɜːk/", "danh từ", "mạng lưới, kết nối", "Build a supportive network of colleagues.", "Xây dựng một mạng lưới đồng nghiệp hỗ trợ nhau.", "social network", "Hệ thống liên kết."),
        ("Security", "/sɪˈkjʊə.rə.ti/", "danh từ", "sự an ninh, bảo mật", "Cyber security defends vital digital infrastructure.", "An ninh mạng bảo vệ hạ tầng số thiết yếu.", "data security", "An toàn bảo mật."),
        ("Privacy", "/ˈprɪv.ə.si/", "danh từ", "quyền riêng tư", "Protect your digital privacy vigilantly.", "Hãy cảnh giác bảo vệ quyền riêng tư kỹ thuật số của bạn.", "user privacy", "Quyền bất khả xâm phạm."),
        ("Access", "/ˈæk.ses/", "danh từ/động từ", "quyền truy cập, tiếp cận", "Ensure equal access to educational resources.", "Đảm bảo quyền tiếp cận công bằng tới nguồn tài nguyên giáo dục.", "gain access", "Khả năng bước vào."),
        ("Modern", "/ˈmɒd.ən/", "tính từ", "hiện đại, tân tiến", "Modern libraries feature collaborative spaces.", "Thư viện hiện đại sở hữu các không gian hợp tác.", "modern society", "Bắt kịp thời đại."),
        ("Ancient", "/ˈeɪn.ʃənt/", "tính từ", "cổ đại, xa xưa", "Ancient wisdom speaks across centuries.", "Trí tuệ cổ đại vẫn lên tiếng qua bao thế kỷ.", "ancient city", "Tồn tại từ ngàn xưa."),
        ("Future", "/ˈfjuː.tʃər/", "danh từ", "tương lai", "Shape the future with compassionate vision.", "Định hình tương lai bằng tầm nhìn nhân ái.", "bright future", "Những ngày phía trước."),
        ("Community", "/kəˈmjuː.nə.ti/", "danh từ", "cộng đồng", "Strong communities support vulnerable members.", "Những cộng đồng vững mạnh nâng đỡ những người yếu thế.", "local community", "Tập thể gắn kết."),
        ("Society", "/səˈsaɪ.ə.ti/", "danh từ", "xã hội", "A civil society values freedom and empathy.", "Một xã hội văn minh coi trọng tự do và sự thấu cảm.", "civil society", "Cộng đồng con người."),
        ("Culture", "/ˈkʌl.tʃər/", "danh từ", "văn hóa", "Cultural heritage connects past with present.", "Di sản văn hóa kết nối quá khứ với hiện tại.", "cultural identity", "Bản sắc văn hiến."),
        ("Education", "/ˌedʒ.uˈkeɪ.ʃən/", "danh từ", "nền giáo dục", "Education is an investment that always pays dividends.", "Giáo dục là khoản đầu tư luôn sinh hoa lợi lớn.", "higher education", "Trồng người."),
        ("Institution", "/ˌɪn.stɪˈtʃuː.ʃən/", "danh từ", "học viện, thể chế", "Academic institutions foster research excellence.", "Các viện nghiên cứu học thuật nuôi dưỡng sự xuất sắc.", "educational institution", "Tổ chức quy mô."),
        ("Government", "/ˈɡʌv.ən.mənt/", "danh từ", "chính phủ, chính quyền", "Transparent governments build civic trust.", "Chính phủ minh bạch xây dựng lòng tin người dân.", "local government", "Bộ máy quản lý đất nước."),
        ("Economy", "/iˈkɒn.ə.mi/", "danh từ", "nền kinh tế", "A resilient economy weathers global crises.", "Một nền kinh tế kiên cường vượt qua các cuộc khủng hoảng toàn cầu.", "global economy", "Hệ thống lưu thông của cải."),
        ("Industry", "/ˈɪn.də.stri/", "danh từ", "ngành công nghiệp", "Renewable energy is a surging industry.", "Năng lượng tái tạo là ngành công nghiệp bùng nổ.", "manufacturing industry", "Ngành sản xuất hàng hóa."),
        ("Global", "/ˈɡləʊ.bəl/", "tính từ", "toàn cầu, bao quát", "Global collaboration solves planetary issues.", "Sự hợp tác toàn cầu giải quyết các vấn đề cấp hành tinh.", "global scale", "Quy mô toàn thế giới."),
        ("Local", "/ˈləʊ.kəl/", "tính từ", "địa phương, sở tại", "Support local organic farmers and markets.", "Hãy ủng hộ nông dân và các khu chợ hữu cơ địa phương.", "local produce", "Trong phạm vi khu vực."),
    ]),
    ("Unit 3: Giáo dục, Giao tiếp & Tư duy", [
        ("Analyze", "/ˈæn.əl.aɪz/", "động từ", "phân tích thấu đáo", "Analyze empirical data before drawing conclusions.", "Hãy phân tích dữ liệu thực nghiệm trước khi rút ra kết luận.", "analyze data", "Mổ xẻ chi tiết vấn đề."),
        ("Concept", "/ˈkɒn.sept/", "danh từ", "khái niệm, ý niệm", "Grasp the core concept behind calculus.", "Nắm vững khái niệm cốt lõi đằng sau môn giải tích.", "basic concept", "Ý niệm nền tảng."),
        ("Theory", "/ˈθɪə.ri/", "danh từ", "lý thuyết, học thuyết", "Scientific theories withstand rigorous testing.", "Các học thuyết khoa học vượt qua những cuộc kiểm chứng gắt gao.", "scientific theory", "Hệ thống lý luận."),
        ("Practice", "/ˈpræk.tɪs/", "danh từ/động từ", "thực hành, rèn luyện", "Theory without practice remains sterile.", "Lý thuyết mà không có thực hành sẽ mãi khô cằn.", "in practice", "Hiện thực hóa kiến thức."),
        ("Research", "/rɪˈsɜːtʃ/", "danh từ/động từ", "nghiên cứu khoa học", "Groundbreaking research uncovers medical cures.", "Nghiên cứu mang tính đột phá hé lộ phương pháp chữa bệnh.", "do research", "Tìm tòi phát hiện mới."),
        ("Evidence", "/ˈev.ɪ.dəns/", "danh từ", "bằng chứng, chứng cứ", "Substantiate claims with verifiable evidence.", "Chứng minh tuyên bố bằng chứng cứ có thể xác minh.", "solid evidence", "Căn cứ xác thực."),
        ("Conclude", "/kənˈkluːd/", "động từ", "kết luận, khép lại", "The investigator concluded after thorough inquiry.", "Điều tra viên kết luận sau cuộc thẩm tra toàn diện.", "conclude a study", "Rút ra phán đoán cuối."),
        ("Evaluate", "/ɪˈvæl.ju.eɪt/", "động từ", "đánh giá, thẩm định", "Evaluate arguments on merit rather than bias.", "Đánh giá các lập luận dựa trên giá trị thay vì định kiến.", "evaluate performance", "Định lượng phẩm chất."),
        ("Identify", "/aɪˈden.tɪ.faɪ/", "động từ", "nhận diện, xác định", "Identify root causes of systemic bottlenecks.", "Xác định nguyên nhân gốc rễ của những điểm nghẽn hệ thống.", "identify problems", "Chỉ mặt đặt tên."),
        ("Demonstrate", "/ˈdem.ən.streɪt/", "động từ", "chứng minh, thị phạm", "Experiments demonstrate physical laws clearly.", "Thí nghiệm chứng minh các định luật vật lý một cách sáng tỏ.", "demonstrate clearly", "Làm mẫu chứng tỏ."),
        ("Illustrate", "/ˈɪl.ə.streɪt/", "động từ", "minh họa, làm rõ", "Diagrams illustrate the cellular process.", "Sơ đồ minh họa rõ nét tiến trình tế bào.", "illustrate a point", "Làm sáng tỏ bằng hình ảnh."),
        ("Describe", "/dɪˈskraɪb/", "động từ", "mô tả, thuật lại", "Describe the sunset with vivid poetic imagery.", "Mô tả hoàng hôn bằng những hình ảnh thi vị sống động.", "describe in detail", "Diễn tả bằng lời."),
        ("Explain", "/ɪkˈspleɪn/", "động từ", "giải thích, phân trần", "Explain complex mathematics in plain language.", "Giải thích toán học phức tạp bằng ngôn từ mộc mạc.", "explain clearly", "Làm cho người khác hiểu."),
        ("Define", "/dɪˈfaɪn/", "động từ", "định nghĩa, vạch rõ", "Define your personal boundaries with firmness.", "Hãy định nghĩa rõ ranh giới cá nhân một cách kiên quyết.", "define clearly", "Xác định phạm vi."),
        ("Express", "/ɪkˈspres/", "động từ", "bày tỏ, diễn đạt", "Express gratitude to mentors who guided you.", "Bày tỏ lòng biết ơn tới những người thầy đã dẫn lối bạn.", "express gratitude", "Bộc lộ suy nghĩ/tình cảm."),
        ("Interpret", "/ɪnˈtɜː.prɪt/", "động từ", "thông dịch, diễn giải", "Scholars interpret ancient hieroglyphs.", "Các học giả diễn giải những chữ tượng hình cổ đại.", "interpret meaning", "Hiểu và dịch nghĩa."),
        ("Summarize", "/ˈsʌm.ər.aɪz/", "động từ", "tóm tắt, tóm lược", "Summarize key findings in three concise bullet points.", "Tóm lược các phát hiện then chốt trong ba gạch đầu dòng ngắn gọn.", "summarize main points", "Rút gọn ý chính."),
        ("Compare", "/kəmˈpeər/", "động từ", "so sánh, đối chiếu", "Compare advantages and drawbacks of each approach.", "So sánh ưu thế và khuyết điểm của từng phương pháp.", "compare with", "Đặt cạnh nhau đối chiếu."),
        ("Contrast", "/kənˈtrɑːst/", "động từ/danh từ", "tương phản, đối lập", "Contrast vibrant colors against dark backgrounds.", "Tạo sự tương phản màu sắc rực rỡ trên nền tối.", "in contrast", "Làm bật sự khác biệt."),
        ("Distinguish", "/dɪˈstɪŋ.ɡwɪʃ/", "động từ", "phân biệt, nhận ra sự khác", "Distinguish facts from emotional rhetoric.", "Phân biệt sự thật khách quan khỏi lời lẽ tu từ cảm tính.", "distinguish between", "Tách bạch rõ ràng."),
        ("Investigate", "/ɪnˈves.tɪ.ɡeɪt/", "động từ", "điều tra, khảo sát", "Scientists investigate anomalies in space data.", "Các nhà khoa học điều tra những điểm bất thường trong dữ liệu vũ trụ.", "investigate thoroughly", "Xem xét kỹ lưỡng."),
        ("Observe", "/əbˈzɜːv/", "động từ", "quan sát, tuân thủ", "Quietly observe natural phenomena in the wild.", "Lặng lẽ quan sát các hiện tượng tự nhiên nơi hoang dã.", "observe carefully", "Nhìn ngắm tinh tế."),
        ("Experiment", "/ɪkˈsper.ɪ.mənt/", "danh từ/động từ", "thí nghiệm, thử nghiệm", "Replicate the physics experiment in lab conditions.", "Lặp lại thí nghiệm vật lý trong điều kiện phòng thí nghiệm.", "conduct an experiment", "Thử nghiệm thực tế."),
        ("Hypothesis", "/haɪˈpɒθ.ə.sɪs/", "danh từ", "giả thuyết khoa học", "Formulate a testable scientific hypothesis.", "Xây dựng một giả thuyết khoa học có thể kiểm chứng được.", "test a hypothesis", "Giả định đặt ra."),
        ("Discover", "/dɪˈskʌv.ər/", "động từ", "phát hiện, khám phá ra", "Astronomers discover exoplanets in distant galaxies.", "Các nhà thiên văn học phát hiện những ngoại hành tinh ở thiên hà xa xôi.", "discover new things", "Tìm ra điều chưa ai biết."),
        ("Invent", "/ɪnˈvent/", "động từ", "phát minh, sáng chế", "Invent tools that elevate human potential.", "Phát minh những công cụ nâng tầm tiềm năng con người.", "invent a device", "Tạo ra cái mới chưa từng có."),
        ("Create", "/kriˈeɪt/", "động từ", "sáng tạo, tạo nên", "Artists create transcendent works of beauty.", "Người nghệ sĩ sáng tạo nên những tác phẩm đẹp siêu việt.", "create value", "Làm nảy sinh cái mới."),
        ("Innovate", "/ˈɪn.ə.veɪt/", "động từ", "đổi mới, cách tân", "Companies that fail to innovate perish quickly.", "Những công ty không biết đổi mới sẽ nhanh chóng lụi tàn.", "innovate constantly", "Cải cách liên tục."),
        ("Design", "/dɪˈzaɪn/", "động từ/danh từ", "thiết kế, bản vẽ", "Design intuitive interfaces that delight users.", "Thiết kế những giao diện trực quan làm hài lòng người dùng.", "design system", "Tạo hình và bố cục."),
        ("Construct", "/kənˈstrʌkt/", "động từ", "xây dựng, kiến thiết", "Construct durable bridges and road networks.", "Xây dựng những cây cầu và mạng lưới đường xá bền vững.", "construct a bridge", "Xây đắp nên công trình."),
    ]),
    ("Unit 4: Quan hệ, Cảm xúc & Nhân cách", [
        ("Relationship", "/rɪˈleɪ.ʃən.ʃɪp/", "danh từ", "mối quan hệ", "Cherish deep and supportive relationships.", "Trân trọng những mối quan hệ sâu sắc và tương trợ.", "close relationship", "Mối liên kết giữa người với người."),
        ("Trust", "/trʌst/", "danh từ/động từ", "lòng tin cậy, tin tưởng", "Trust takes years to build and seconds to break.", "Lòng tin mất nhiều năm để gây dựng và chỉ vài giây để đánh mất.", "build trust", "Sự tín nhiệm son sắt."),
        ("Respect", "/rɪˈspekt/", "danh từ/động từ", "sự tôn trọng, kính trọng", "Treat all beings with dignity and respect.", "Đối xử với mọi sinh linh bằng phẩm giá và sự tôn trọng.", "mutual respect", "Kính cẩn trọng thị."),
        ("Honest", "/ˈɒn.ɪst/", "tính từ", "thật thà, trung thực", "Honest dialogue heals deep misunderstandings.", "Đối thoại chân thành xoa dịu những hiểu lầm sâu sắc.", "honest person", "Âm 'h' câm: /ˈɒn.ɪst/."),
        ("Loyal", "/ˈlɔɪ.əl/", "tính từ", "trung thành, son sắt", "A loyal companion stands by you in storms.", "Người bạn đồng hành trung thành luôn kề bên bạn trong giông tố.", "loyal friend", "Trước sau như một."),
        ("Patient", "/ˈpeɪ.ʃənt/", "tính từ/danh từ", "kiên nhẫn, bệnh nhân", "Be patient with yourself as you acquire skills.", "Hãy kiên nhẫn với bản thân khi bạn đang tiếp thu các kỹ năng.", "patient listener", "Nhẫn nại chờ đợi."),
        ("Generous", "/ˈdʒen.ər.əs/", "tính từ", "hào phóng, rộng lượng", "Generous souls share wisdom and resources.", "Những tâm hồn rộng lượng luôn sẻ chia tri thức và nguồn lực.", "generous donor", "Cho đi không toan tính."),
        ("Polite", "/pəˈlaɪt/", "tính từ", "lịch thiệp, lễ phép", "Polite manners open doors everywhere.", "Cử chỉ lịch thiệp mở ra mọi cánh cửa ở bất cứ nơi đâu.", "polite behavior", "Cư xử nhã nhặn."),
        ("Brave", "/breɪv/", "tính từ", "dũng cảm, can trường", "Brave hearts confront injustice without wavering.", "Những trái tim dũng cảm đối diện với bất công mà không hề nao núng.", "brave soldier", "Không sợ hãi hiểm nguy."),
        ("Confident", "/ˈkɒn.fɪ.dənt/", "tính từ", "tự tin, đĩnh đạc", "Preparation breeds quiet, unwavering confidence.", "Sự chuẩn bị kỹ lưỡng sinh ra lòng tự tin thầm lặng mà vững vàng.", "self confident", "Tin vào bản thân."),
        ("Curious", "/ˈkjʊə.ri.əs/", "tính từ", "tò mò, ham học hỏi", "Curious minds explore uncharted horizons.", "Những tâm trí ham học hỏi khám phá những chân trời chưa ai tới.", "stay curious", "Khát khao hiểu biết."),
        ("Creative", "/kriˈeɪ.tɪv/", "tính từ", "sáng tạo", "Creative thinking synthesizes disparate insights.", "Tư duy sáng tạo tổng hòa những góc nhìn khác biệt.", "creative thinker", "Khả năng sáng tạo cái mới."),
        ("Determined", "/dɪˈtɜː.mɪnd/", "tính từ", "quyết tâm, kiên định", "Determined climbers conquer steep peaks.", "Những người leo núi kiên định chinh phục các đỉnh cao hiểm trở.", "strongly determined", "Giữ vững ý chí."),
        ("Independent", "/ˌɪn.dɪˈpen.dənt/", "tính từ", "độc lập, tự chủ", "Independent thinkers evaluate claims critically.", "Những người tư duy độc lập đánh giá các luận điểm một cách phản biện.", "financially independent", "Tự đứng trên đôi chân mình."),
        ("Responsible", "/rɪˈspɒn.sə.bəl/", "tính từ", "có trách nhiệm", "Responsible stewards protect natural habitats.", "Những người quản lý có trách nhiệm bảo vệ các môi trường sống tự nhiên.", "responsible citizen", "Làm tròn bổn phận."),
        ("Optimistic", "/ˌɒp.tɪˈmɪs.tɪk/", "tính từ", "lạc quan, yêu đời", "An optimistic outlook sees potential in adversity.", "Một góc nhìn lạc quan nhìn thấy tiềm năng ngay trong nghịch cảnh.", "optimistic view", "Tin tưởng tương lai tốt đẹp."),
        ("Pessimistic", "/ˌpes.ɪˈmɪs.tɪk/", "tính từ", "bi quan", "Avoid chronic pessimistic rumination.", "Hãy tránh việc trầm ngâm suy nghĩ bi quan kinh niên.", "pessimistic attitude", "Nhìn sự việc theo chiều hướng xấu."),
        ("Emotional", "/ɪˈməʊ.ʃən.əl/", "tính từ", "thuộc về cảm xúc", "Cultivate emotional balance under stress.", "Nuôi dưỡng sự cân bằng cảm xúc dưới áp lực.", "emotional intelligence", "Liên quan tới rung động trái tim."),
        ("Sensitive", "/ˈsen.sɪ.tɪv/", "tính từ", "nhạy cảm, tinh tế", "A sensitive writer captures quiet heartaches.", "Một nhà văn nhạy cảm nắm bắt được những nỗi đau thầm kín.", "sensitive skin", "Dễ cảm nhận biến đổi."),
        ("Enthusiastic", "/ɪnˌθjuː.ziˈæs.tɪk/", "tính từ", "nhiệt huyết, hăng hái", "Enthusiastic volunteers planted hundreds of trees.", "Những tình nguyện viên nhiệt huyết đã trồng hàng trăm cây xanh.", "enthusiastic support", "Năng lượng bùng cháy."),
        ("Inspirational", "/ˌɪn.spɪˈreɪ.ʃən.əl/", "tính từ", "truyền cảm hứng", "Read inspirational biographies of luminaries.", "Đọc những cuốn tiểu sử truyền cảm hứng của các bậc vĩ nhân.", "inspirational story", "Thổi bùng ý chí người khác."),
        ("Sympathetic", "/ˌsɪm.pəˈθet.ɪk/", "tính từ", "thông cảm, đồng cảm", "A sympathetic listener heals invisible wounds.", "Người lắng nghe biết thông cảm xoa dịu những vết thương vô hình.", "sympathetic smile", "Thương cảm sẻ chia."),
        ("Affection", "/əˈfek.ʃən/", "danh từ", "tình cảm yêu thương", "Show sincere affection to your family.", "Hãy bày tỏ tình cảm yêu thương chân thành tới gia đình bạn.", "deep affection", "Tình cảm quyến luyến."),
        ("Compassion", "/kəmˈpæʃ.ən/", "danh từ", "lòng trắc ẩn, từ bi", "Compassion is the hallmark of noble spirit.", "Lòng trắc ẩn là dấu ấn của một tâm hồn cao thượng.", "show compassion", "Tấm lòng yêu thương muôn loài."),
        ("Forgive", "/fəˈɡɪv/", "động từ", "tha thứ, bao dung", "Forgiving others frees your own heart.", "Tha thứ cho người khác giải phóng chính trái tim bạn.", "forgive and forget", "Bỏ qua lỗi lầm."),
        ("Apologize", "/əˈpɒl.ə.dʒaɪz/", "động từ", "xin lỗi chân thành", "Apologize sincerely when you make mistakes.", "Hãy xin lỗi chân thành khi bạn phạm sai lầm.", "apologize for", "Nhận lỗi về mình."),
        ("Appreciate", "/əˈpriː.ʃi.eɪt/", "động từ", "trân trọng, đánh giá cao", "Appreciate the little blessings of each day.", "Hãy trân trọng những điều tốt lành nho nhỏ mỗi ngày.", "greatly appreciate", "Biết ơn và quý trọng."),
        ("Encourage", "/ɪnˈkʌr.ɪdʒ/", "động từ", "khích lệ, động viên", "Encourage younger learners to persevere.", "Khích lệ các bạn nhỏ kiên trì theo đuổi việc học.", "encourage someone", "Tiếp thêm niềm tin."),
        ("Support", "/səˈpɔːt/", "danh từ/động từ", "ủng hộ, nâng đỡ", "Strong pillars support magnificent structures.", "Những cột trụ vững chãi nâng đỡ các công trình tráng lệ.", "support each other", "Hậu thuẫn vững vàng."),
        ("Comfort", "/ˈkʌm.fət/", "danh từ/động từ", "sự an ủi, tiện nghi", "Words of solace bring comfort in grief.", "Những lời an ủi đem lại sự thanh thản trong đau buồn.", "find comfort", "Êm ái xoa dịu."),
    ])
]

for u_title, w_list in b1_units:
    for item in w_list:
        add_e("B1", u_title, *item)

print(f"Generated B1 words. Total so far: {len(b1_b2_c1)}")

# Save B1 to file
with open("scripts/en_b1.json", "w", encoding="utf-8") as f:
    json.dump(b1_b2_c1, f, ensure_ascii=False, indent=2)
