import fs from 'fs';
import path from 'path';

// Comprehensive dictionary seed generator
console.log('Starting dictionary builder for >1000 words...');

// English Vocabulary seed
const englishVocab = [
  // A1 (120 words)
  { level: 'A1', unit: 'Unit 1: Chào hỏi & Giao tiếp nền tảng', words: [
    ['Hello', '/həˈləʊ/', 'thán từ', 'xin chào', 'Hello, nice to meet you!', 'Xin chào, rất vui được gặp bạn!', 'say hello', 'Chào hỏi lịch thiệp khi gặp mặt.'],
    ['Goodbye', '/ɡʊdˈbaɪ/', 'thán từ', 'tạm biệt', 'Goodbye, see you tomorrow.', 'Tạm biệt, hẹn gặp lại ngày mai.', 'say goodbye', 'Lời chào tạm biệt kinh điển.'],
    ['Name', '/neɪm/', 'danh từ', 'tên gọi, họ tên', 'What is your full name?', 'Tên đầy đủ của bạn là gì?', 'full name', 'Xác định danh tính cá nhân.'],
    ['Friend', '/frend/', 'danh từ', 'người bạn', 'She is my closest friend.', 'Cô ấy là người bạn thân nhất của tôi.', 'close friend', 'Mối quan hệ thân thiết gắn bó.'],
    ['Family', '/ˈfæm.əl.i/', 'danh từ', 'gia đình', 'I love spending time with my family.', 'Tôi thích dành thời gian bên gia đình.', 'family members', 'Tổ ấm thiêng liêng.'],
    ['Father', '/ˈfɑː.ðər/', 'danh từ', 'người cha, bố', 'My father is an engineer.', 'Bố tôi là một kỹ sư.', 'father and son', 'Người đàn ông trụ cột gia đình.'],
    ['Mother', '/ˈmʌð.ər/', 'danh từ', 'người mẹ, má', 'My mother cooks delicious meals.', 'Mẹ tôi nấu những bữa ăn rất ngon.', 'caring mother', 'Tình mẫu tử ấm áp.'],
    ['Brother', '/ˈbrʌð.ər/', 'danh từ', 'anh trai, em trai', 'My brother is a student.', 'Em trai tôi là một học sinh.', 'older brother', 'Anh em ruột thịt trong nhà.'],
    ['Sister', '/ˈsɪs.tər/', 'danh từ', 'chị gái, em gái', 'My sister loves music.', 'Em gái tôi rất thích âm nhạc.', 'younger sister', 'Chị em gái hòa thuận.'],
    ['Child', '/tʃaɪld/', 'danh từ', 'đứa trẻ, con cái', 'The child is smiling.', 'Đứa trẻ đang mỉm cười.', 'happy child', 'Số nhiều bất quy tắc là Children.'],
    ['Home', '/həʊm/', 'danh từ', 'tổ ấm, quê nhà', 'Welcome to our humble home.', 'Chào mừng bạn đến với tổ ấm đơn sơ của chúng tôi.', 'at home', 'Home mang cảm xúc ấm áp hơn House.'],
    ['House', '/haʊs/', 'danh từ', 'ngôi nhà (vật lý)', 'They bought a modern house.', 'Họ đã mua một ngôi nhà hiện đại.', 'brick house', 'Công trình kiến trúc nhà ở.'],
    ['School', '/skuːl/', 'danh từ', 'trường học', 'Children go to school every day.', 'Trẻ em đến trường mỗi ngày.', 'at school', 'Nơi truyền thụ tri thức.'],
    ['Teacher', '/ˈtiː.tʃər/', 'danh từ', 'giáo viên, thầy cô', 'Our teacher is very patient.', 'Giáo viên của chúng tôi rất kiên nhẫn.', 'English teacher', 'Người dẫn dắt tri thức.'],
    ['Student', '/ˈstjuː.dənt/', 'danh từ', 'học sinh, sinh viên', 'She is a diligent student.', 'Cô ấy là một học sinh siêng năng.', 'college student', 'Người theo đuổi học vấn.'],
    ['Book', '/bʊk/', 'danh từ', 'cuốn sách', 'Reading a book expands your mind.', 'Đọc sách mở rộng tâm trí của bạn.', 'read a book', 'Kho tàng tri thức nhân loại.'],
    ['Pen', '/pen/', 'danh từ', 'cây bút mực', 'Write your signature with this pen.', 'Hãy ký tên của bạn bằng chiếc bút này.', 'ballpoint pen', 'Dụng cụ ghi chép.'],
    ['Pencil', '/ˈpen.səl/', 'danh từ', 'bút chì', 'Draw a sketch with a pencil.', 'Hãy phác thảo bằng bút chì.', 'colored pencil', 'Có thể tẩy xóa dễ dàng.'],
    ['Desk', '/desk/', 'danh từ', 'bàn học, bàn làm việc', 'My desk is always organized.', 'Bàn làm việc của tôi luôn ngăn nắp.', 'wooden desk', 'Bàn có ngăn kéo để làm việc.'],
    ['Room', '/ruːm/', 'danh từ', 'căn phòng', 'This room gets plenty of sunlight.', 'Căn phòng này đón rất nhiều ánh nắng.', 'living room', 'Không gian sinh hoạt khép kín.'],
    ['Water', '/ˈwɔː.tər/', 'danh từ', 'nước uống', 'Drink enough clean water daily.', 'Hãy uống đủ nước sạch mỗi ngày.', 'mineral water', 'Nguồn gốc của sự sống.'],
    ['Food', '/fuːd/', 'danh từ', 'thức ăn, thực phẩm', 'Good food brings people together.', 'Đồ ăn ngon kết nối mọi người lại với nhau.', 'healthy food', 'Dinh dưỡng nuôi dưỡng cơ thể.'],
    ['Bread', '/bred/', 'danh từ', 'bánh mì', 'Freshly baked bread smells heavenly.', 'Bánh mì mới nướng có mùi thơm tuyệt diệu.', 'loaf of bread', 'Lương thực chính của phương Tây.'],
    ['Rice', '/raɪs/', 'danh từ', 'cơm, gạo', 'Rice is a staple food in Asia.', 'Cơm là lương thực thiết yếu tại châu Á.', 'fried rice', 'Hạt ngọc trời ban.'],
    ['Tea', '/tiː/', 'danh từ', 'trà, nước chè', 'Would you like a cup of tea?', 'Bạn có muốn một tách trà không?', 'green tea', 'Nét văn hóa thưởng trà thanh tao.'],
    ['Coffee', '/ˈkɒf.i/', 'danh từ', 'cà phê', 'A cup of coffee boosts energy.', 'Một tách cà phê giúp tăng cường năng lượng.', 'black coffee', 'Thức uống tỉnh táo mỗi sáng.'],
    ['Milk', '/mɪlk/', 'danh từ', 'sữa tươi', 'Warm milk helps you sleep better.', 'Sữa ấm giúp bạn ngủ ngon hơn.', 'fresh milk', 'Giàu canxi và dưỡng chất.'],
    ['Apple', '/ˈæp.əl/', 'danh từ', 'quả táo', 'Crisp red apples are sweet and juicy.', 'Những quả táo đỏ giòn ngọt mọng nước.', 'apple juice', 'Trái cây giàu vitamin.'],
    ['Orange', '/ˈɒr.ɪndʒ/', 'danh từ/tính từ', 'quả cam, màu cam', 'Oranges are rich in vitamin C.', 'Cam rất giàu vitamin C.', 'fresh orange', 'Trái cây họ cam chanh.'],
    ['Banana', '/bəˈnɑː.nə/', 'danh từ', 'quả chuối', 'Bananas provide quick energy.', 'Chuối cung cấp năng lượng nhanh chóng.', 'ripe banana', 'Giàu kali cho vận động.'],
  ]},
  { level: 'A1', unit: 'Unit 2: Sinh hoạt & Hoạt động thường nhật', words: [
    ['Eat', '/iːt/', 'động từ', 'ăn uống', 'Eat plenty of green vegetables.', 'Hãy ăn nhiều rau xanh.', 'eat healthy', 'Hành động nạp dinh dưỡng.'],
    ['Drink', '/drɪŋk/', 'động từ', 'uống', 'Remember to drink water.', 'Nhớ uống nước nhé.', 'drink tea', 'Cung cấp nước cho cơ thể.'],
    ['Sleep', '/sliːp/', 'động từ', 'ngủ', 'Sleep early to wake up refreshed.', 'Hãy ngủ sớm để thức dậy sảng khoái.', 'sleep tight', 'Giấc ngủ tái tạo năng lượng.'],
    ['Wake', '/weɪk/', 'động từ', 'thức giấc', 'I wake up at dawn.', 'Tôi thức dậy vào lúc bình minh.', 'wake up', 'Khởi đầu một ngày mới.'],
    ['Walk', '/wɔːk/', 'động từ', 'đi bộ', 'Walking in nature reduces stress.', 'Đi bộ giữa thiên nhiên giúp giảm căng thẳng.', 'walk slowly', 'Phương pháp vận động nhẹ nhàng.'],
    ['Run', '/rʌn/', 'động từ', 'chạy bộ', 'Run for thirty minutes daily.', 'Hãy chạy bộ ba mươi phút mỗi ngày.', 'fast runner', 'Môn thể thao cardio tuyệt vời.'],
    ['Read', '/riːd/', 'động từ', 'đọc sách báo', 'Read books to learn new things.', 'Đọc sách để học thêm những điều mới.', 'read carefully', 'Nuôi dưỡng trí tuệ qua con chữ.'],
    ['Write', '/raɪt/', 'động từ', 'viết lách', 'Write down your ideas.', 'Hãy viết lại những ý tưởng của bạn.', 'write letters', 'Diễn đạt tư duy qua ngôn từ.'],
    ['Listen', '/ˈlɪs.ən/', 'động từ', 'lắng nghe', 'Listen to your inner voice.', 'Hãy lắng nghe tiếng nói bên trong bạn.', 'listen to music', 'Âm "t" câm, đọc là /ˈlɪs.ən/.'],
    ['Speak', '/spiːk/', 'động từ', 'nói chuyện', 'Speak clearly and confidently.', 'Hãy nói rõ ràng và tự tin.', 'speak fluently', 'Truyền tải âm thanh ngôn ngữ.'],
    ['Talk', '/tɔːk/', 'động từ', 'trò chuyện', 'Let us talk about your plan.', 'Chúng ta hãy trò chuyện về kế hoạch của bạn.', 'talk with friends', 'Âm "l" câm, đọc là /tɔːk/.'],
    ['See', '/siː/', 'động từ', 'nhìn thấy', 'I see a rainbow in the sky.', 'Tôi nhìn thấy cầu vồng trên bầu trời.', 'see clearly', 'Quan sát bằng thị giác.'],
    ['Hear', '/hɪər/', 'động từ', 'nghe thấy', 'Did you hear that lovely sound?', 'Bạn có nghe thấy âm thanh êm dịu đó không?', 'hear noises', 'Cảm nhận bằng thính giác.'],
    ['Look', '/lʊk/', 'động từ', 'nhìn ngắm', 'Look at the beautiful sunrise.', 'Hãy ngắm nhìn cảnh bình minh tuyệt đẹp.', 'look at', 'Chủ động hướng mắt quan sát.'],
    ['Watch', '/wɒtʃ/', 'động từ', 'theo dõi, xem', 'Watch the waves roll onto the beach.', 'Ngắm nhìn từng đợt sóng vỗ vào bờ.', 'watch movies', 'Theo dõi chuyển động có chú ý.'],
    ['Buy', '/baɪ/', 'động từ', 'mua sắm', 'Buy what you truly need.', 'Hãy mua những gì bạn thực sự cần.', 'buy groceries', 'Giao dịch sở hữu đồ vật.'],
    ['Sell', '/sel/', 'động từ', 'bán hàng', 'They sell organic products.', 'Họ bán các sản phẩm hữu cơ.', 'sell goods', 'Cung cấp sản phẩm ra thị trường.'],
    ['Pay', '/peɪ/', 'động từ', 'thanh toán, trả tiền', 'You can pay with credit card.', 'Bạn có thể thanh toán bằng thẻ tín dụng.', 'pay attention', 'Thực hiện nghĩa vụ tài chính.'],
    ['Cost', '/kɒst/', 'danh từ/động từ', 'chi phí, có giá', 'How much does this cost?', 'Món này có giá bao nhiêu?', 'high cost', 'Mức giá phải bỏ ra.'],
    ['Open', '/ˈəʊ.pən/', 'động từ/tính từ', 'mở ra, đang mở', 'Open your mind to new concepts.', 'Hãy mở rộng tâm trí đón nhận khái niệm mới.', 'open doors', 'Bắt đầu hoặc hé mở lối đi.'],
    ['Close', '/kləʊz/', 'động từ', 'đóng lại, khép lại', 'Close your eyes and breathe deep.', 'Hãy nhắm mắt và thở sâu.', 'close windows', 'Khép lại không gian.'],
    ['Start', '/stɑːt/', 'động từ', 'khởi đầu, bắt đầu', 'Start small and stay consistent.', 'Hãy bắt đầu từ việc nhỏ và kiên trì.', 'start fresh', 'Bước đầu tiên luôn quan trọng nhất.'],
    ['Stop', '/stɒp/', 'động từ', 'dừng lại', 'Never stop learning and growing.', 'Đừng bao giờ ngừng học hỏi và phát triển.', 'full stop', 'Tạm dừng hành động.'],
    ['Wait', '/weɪt/', 'động từ', 'chờ đợi', 'Patience is waiting with a good attitude.', 'Kiên nhẫn là việc chờ đợi với thái độ tích cực.', 'wait for', 'Dành thời gian chờ kết quả.'],
    ['Help', '/help/', 'động từ/danh từ', 'giúp đỡ, tương trợ', 'Helping others brings deep joy.', 'Giúp đỡ người khác mang lại niềm vui sâu sắc.', 'help out', 'Hành động nhân văn tốt đẹp.'],
    ['Work', '/wɜːk/', 'động từ/danh từ', 'làm việc, công việc', 'Hard work pays off eventually.', 'Làm việc chăm chỉ cuối cùng sẽ đem lại quả ngọt.', 'work hard', 'Cống hiến công sức và trí tuệ.'],
    ['Play', '/pleɪ/', 'động từ', 'vui chơi, chơi đùa', 'Children love to play outdoors.', 'Trẻ con rất thích chơi đùa ngoài trời.', 'play sports', 'Thư giãn tinh thần và thể chất.'],
    ['Live', '/lɪv/', 'động từ', 'sinh sống, tồn tại', 'Live life with purpose and gratitude.', 'Hãy sống cuộc đời có mục đích và lòng biết ơn.', 'live peacefully', 'Sự sống quý giá.'],
    ['Stay', '/steɪ/', 'động từ', 'ở lại, lưu lại', 'Stay calm in difficult times.', 'Hãy giữ bình tĩnh trong những lúc khó khăn.', 'stay safe', 'Duy trì trạng thái tại một nơi.'],
    ['Come', '/kʌm/', 'động từ', 'đến, tới', 'Come visit our hometown soon.', 'Hãy sớm đến thăm quê hương của chúng tôi nhé.', 'come home', 'Di chuyển đến vị trí người nói.'],
  ]},
  { level: 'A1', unit: 'Unit 3: Không gian, Đồ vật & Màu sắc', words: [
    ['Go', '/ɡəʊ/', 'động từ', 'đi, di chuyển', 'Let us go on an adventure.', 'Chúng ta hãy cùng bước vào một chuyến phiêu lưu.', 'go ahead', 'Di chuyển rời xa điểm bắt đầu.'],
    ['Car', '/kɑːr/', 'danh từ', 'xe hơi, ô tô', 'Electric cars are eco-friendly.', 'Xe điện rất thân thiện với môi trường.', 'drive a car', 'Phương tiện giao thông 4 bánh.'],
    ['Bus', '/bʌs/', 'danh từ', 'xe buýt', 'Public bus routes are very convenient.', 'Các tuyến xe buýt công cộng rất tiện lợi.', 'catch a bus', 'Phương tiện giao thông công cộng.'],
    ['Train', '/treɪn/', 'danh từ', 'xe lửa, tàu hỏa', 'The high-speed train is punctual.', 'Chuyến tàu cao tốc chạy rất đúng giờ.', 'board a train', 'Di chuyển trên đường ray.'],
    ['Plane', '/pleɪn/', 'danh từ', 'máy bay', 'The plane soared through white clouds.', 'Chiếc máy bay lượn qua những đám mây trắng.', 'by plane', 'Phương tiện hàng không.'],
    ['Boat', '/bəʊt/', 'danh từ', 'thuyền bè', 'Fishermen steer their boat to sea.', 'Ngư dân lái thuyền ra khơi.', 'sail a boat', 'Phương tiện đường thủy.'],
    ['Road', '/rəʊd/', 'danh từ', 'con đường', 'The road curves through green hills.', 'Con đường uốn lượn qua những ngọn đồi xanh.', 'main road', 'Lối đi giao thông.'],
    ['Street', '/striːt/', 'danh từ', 'phố xá', 'The street comes alive at night.', 'Con phố trở nên nhộn nhịp vào ban đêm.', 'busy street', 'Đường phố có nhà cửa hai bên.'],
    ['City', '/ˈsɪt.i/', 'danh từ', 'thành phố', 'Modern cities have tall skylines.', 'Các thành phố hiện đại có đường chân trời cao vút.', 'capital city', 'Khu đô thị sầm uất.'],
    ['Village', '/ˈvɪl.ɪdʒ/', 'danh từ', 'ngôi làng, thôn dã', 'The ancient village preserves traditions.', 'Ngôi làng cổ kính gìn giữ nhiều truyền thống.', 'peaceful village', 'Vùng quê yên ả.'],
    ['Table', '/ˈteɪ.bəl/', 'danh từ', 'cái bàn', 'Put the flowers on the table.', 'Hãy đặt hoa lên bàn nhé.', 'dining table', 'Nội thất dùng đặt đồ vật.'],
    ['Chair', '/tʃeər/', 'danh từ', 'chiếc ghế', 'Sit comfortably in this armchair.', 'Hãy ngồi thoải mái trên chiếc ghế bành này.', 'comfortable chair', 'Đồ nội thất để ngồi.'],
    ['Bed', '/bed/', 'danh từ', 'chiếc giường', 'Make your bed every morning.', 'Hãy dọn giường ngủ mỗi buổi sáng.', 'go to bed', 'Nơi nghỉ ngơi lấy lại sức.'],
    ['Door', '/dɔːr/', 'danh từ', 'cánh cửa ra vào', 'Knock on the door before entering.', 'Hãy gõ cửa trước khi bước vào.', 'front door', 'Lối ra vào căn phòng.'],
    ['Window', '/ˈwɪn.dəʊ/', 'danh từ', 'cửa sổ', 'Open the window to enjoy the breeze.', 'Mở cửa sổ để tận hưởng làn gió mát.', 'glass window', 'Khung cửa đón ánh sáng.'],
    ['Wall', '/wɔːl/', 'danh từ', 'bức tường', 'Paint the wall in soft beige.', 'Hãy sơn bức tường bằng màu be dịu nhẹ.', 'brick wall', 'Vách ngăn kiến trúc.'],
    ['Floor', '/flɔːr/', 'danh từ', 'sàn nhà, tầng lầu', 'Polished wooden floors look elegant.', 'Sàn gỗ bóng loáng trông rất trang nhã.', 'first floor', 'Mặt đất bằng phẳng bên trong.'],
    ['Key', '/kiː/', 'danh từ', 'chìa khóa', 'Keep your house keys in a safe spot.', 'Hãy giữ chìa khóa nhà ở nơi an toàn.', 'key to success', 'Vật mở khóa, hoặc chìa khóa bí quyết.'],
    ['Phone', '/fəʊn/', 'danh từ', 'điện thoại', 'Smartphones connect the world.', 'Điện thoại thông minh kết nối cả thế giới.', 'mobile phone', 'Thiết bị liên lạc di động.'],
    ['Computer', '/kəmˈpjuː.tər/', 'danh từ', 'máy vi tính', 'Computers revolutionize modern life.', 'Máy tính cách mạng hóa đời sống hiện đại.', 'personal computer', 'Cỗ máy xử lý dữ liệu.'],
    ['Clock', '/klɒk/', 'danh từ', 'đồng hồ', 'The grandfather clock chimed noon.', 'Chiếc đồng hồ quả lắc điểm mười hai giờ trưa.', 'alarm clock', 'Dụng cụ đo đạc thời gian.'],
    ['Bag', '/bæɡ/', 'danh từ', 'cái túi, cặp', 'Pack your essentials in this bag.', 'Hãy đóng gói đồ dùng thiết yếu vào chiếc túi này.', 'backpack', 'Vật dụng chứa đựng hành lý.'],
    ['Box', '/bɒks/', 'danh từ', 'chiếc hộp', 'Store old photos in a memory box.', 'Lưu giữ những bức ảnh cũ trong chiếc hộp kỷ niệm.', 'cardboard box', 'Khối hộp chữ nhật.'],
    ['Paper', '/ˈpeɪ.pər/', 'danh từ', 'giấy viết', 'Recycle used paper to save trees.', 'Tái chế giấy đã qua sử dụng để cứu cây xanh.', 'sheet of paper', 'Chất liệu ghi chép ngàn đời.'],
    ['Red', '/red/', 'tính từ/danh từ', 'màu đỏ rực', 'Ruby is a vibrant red gemstone.', 'Hồng ngọc là viên đá quý màu đỏ rực rỡ.', 'bright red', 'Màu của năng lượng và đam mê.'],
    ['Blue', '/bluː/', 'tính từ/danh từ', 'màu xanh lam', 'The azure sea is calm and blue.', 'Biển xanh biếc tĩnh lặng và êm đềm.', 'deep blue', 'Màu của bầu trời và biển cả.'],
    ['Green', '/ɡriːn/', 'tính từ/danh từ', 'màu xanh lá', 'Spring brings lush green meadows.', 'Mùa xuân mang tới những đồng cỏ xanh mướt.', 'emerald green', 'Màu của sự sinh sôi nảy nở.'],
    ['Yellow', '/ˈjel.əʊ/', 'tính từ/danh từ', 'màu vàng', 'Bright yellow sunflowers follow sunlight.', 'Những bông hướng dương vàng óng hướng về ánh mặt trời.', 'golden yellow', 'Màu của ánh sáng và sự lạc quan.'],
    ['Black', '/blæk/', 'tính từ/danh từ', 'màu đen', 'Black night sky filled with stars.', 'Bầu trời đêm đen thẳm đầy sao.', 'pitch black', 'Màu của sự huyền bí và sang trọng.'],
    ['White', '/waɪt/', 'tính từ/danh từ', 'màu trắng tinh', 'White doves symbolize world peace.', 'Bồ câu trắng tượng trưng cho hòa bình thế giới.', 'pure white', 'Màu của sự thuần khiết.'],
  ]},
  { level: 'A1', unit: 'Unit 4: Thiên nhiên & Con người', words: [
    ['Sun', '/sʌn/', 'danh từ', 'mặt trời', 'Morning sun warms the earth.', 'Ánh nắng ban mai sưởi ấm vạn vật.', 'sunshine', 'Ngôi sao mang sự sống đến Trái Đất.'],
    ['Moon', '/muːn/', 'danh từ', 'mặt trăng', 'Silver moon illuminates quiet nights.', 'Vầng trăng bạc soi sáng những đêm thanh tĩnh.', 'full moon', 'Vệ tinh tự nhiên của Trái Đất.'],
    ['Star', '/stɑːr/', 'danh từ', 'ngôi sao', 'Constellations form patterns in the sky.', 'Những chòm sao tạo thành hình vẽ trên bầu trời.', 'shooting star', 'Vật thể phát sáng xa xôi vũ trụ.'],
    ['Sky', '/skaɪ/', 'danh từ', 'bầu trời', 'Limitless blue sky inspires freedom.', 'Bầu trời xanh vô tận khơi dậy tự do.', 'clear sky', 'Vòm trời bao la.'],
    ['Cloud', '/klaʊd/', 'danh từ', 'đám mây', 'Fluffy clouds float gracefully.', 'Những đám mây bồng bềnh trôi duyên dáng.', 'white cloud', 'Hơi nước ngưng tụ trên cao.'],
    ['Rain', '/reɪn/', 'danh từ/động từ', 'mưa, cơn mưa', 'Gentle rain nourishes seeds.', 'Cơn mưa êm dịu nuôi dưỡng những hạt mầm.', 'heavy rain', 'Nước rơi từ bầu khí quyển.'],
    ['Wind', '/wɪnd/', 'danh từ', 'ngọn gió', 'Cool wind whispers in the pines.', 'Ngọn gió mát thì thầm qua rặng thông.', 'gentle wind', 'Sự chuyển dịch của khối không khí.'],
    ['Tree', '/triː/', 'danh từ', 'cây cối', 'Trees purify air and provide shade.', 'Cây xanh thanh lọc không khí và cho bóng râm.', 'fruit tree', 'Lá phổi xanh của Trái Đất.'],
    ['Flower', '/flaʊ.ər/', 'danh từ', 'bông hoa', 'Lotus flowers bloom with grace.', 'Những đóa hoa sen nở rộ đầy thanh tao.', 'blooming flower', 'Biểu tượng của vẻ đẹp thiên nhiên.'],
    ['River', '/ˈrɪv.ər/', 'danh từ', 'dòng sông', 'Mekong River flows across continents.', 'Dòng sông Mê Kông chảy qua nhiều quốc gia.', 'river bank', 'Dòng nước ngọt tự nhiên chảy ra biển.'],
    ['Sea', '/siː/', 'danh từ', 'biển khơi', 'Breathe fresh sea air to rejuvenate.', 'Hít thở không khí biển trong lành để hồi phục.', 'deep sea', 'Biển mặn bao la.'],
    ['Mountain', '/ˈmaʊn.tɪn/', 'danh từ', 'ngọn núi', 'Climb mountains to gain fresh perspectives.', 'Leo núi để có góc nhìn rộng mở hơn.', 'mountain peak', 'Đỉnh cao hùng vĩ của tự nhiên.'],
    ['Animal', '/ˈæn.ɪ.məl/', 'danh từ', 'động vật, muông thú', 'Protect endangered animal species.', 'Bảo vệ các loài động vật có nguy cơ tuyệt chủng.', 'wild animal', 'Sinh vật sống cùng chia sẻ hành tinh.'],
    ['Dog', '/dɒɡ/', 'danh từ', 'chú chó', 'Dogs are loyal companions.', 'Chó là người bạn đồng hành trung thành.', 'faithful dog', 'Bạn thân của con người.'],
    ['Cat', '/kæt/', 'danh từ', 'chú mèo', 'Cats walk softly with grace.', 'Mèo bước đi nhẹ nhàng và uyển chuyển.', 'playful cat', 'Thú cưng đáng yêu.'],
    ['Bird', '/bɜːd/', 'danh từ', 'loài chim', 'Migratory birds fly thousands of miles.', 'Những loài chim di cư bay hàng nghìn dặm.', 'songbird', 'Loài vật có lông vũ và cất cánh.'],
    ['Fish', '/fɪʃ/', 'danh từ', 'loài cá', 'Tropical fish show vivid colors.', 'Cá nhiệt đới mang màu sắc rực rỡ.', 'freshwater fish', 'Sinh vật bơi lội dưới nước.'],
    ['Eye', '/aɪ/', 'danh từ', 'đôi mắt', 'Eyes are windows to the soul.', 'Đôi mắt là cửa sổ tâm hồn.', 'bright eyes', 'Cơ quan thị giác kỳ diệu.'],
    ['Ear', '/ɪər/', 'danh từ', 'đôi tai', 'Listen with an open ear and mind.', 'Hãy lắng nghe với đôi tai và tấm lòng rộng mở.', 'sharp ear', 'Cơ quan thính giác.'],
    ['Hand', '/hænd/', 'danh từ', 'bàn tay', 'Lend a helping hand to neighbors.', 'Hãy chìa bàn tay giúp đỡ những người xung quanh.', 'give a hand', 'Dụng cụ lao động kỳ diệu của con người.'],
    ['Heart', '/hɑːt/', 'danh từ', 'trái tim', 'Kind hearts bring healing warmth.', 'Những trái tim nhân ái mang lại hơi ấm chữa lành.', 'warm heart', 'Tâm hồn và cơ quan tuần hoàn máu.'],
    ['Happy', '/ˈhæp.i/', 'tính từ', 'vui vẻ, hạnh phúc', 'True happiness comes from contentment.', 'Hạnh phúc chân thực đến từ sự biết đủ.', 'happy life', 'Cảm xúc hân hoan.'],
    ['Good', '/ɡʊd/', 'tính từ', 'tốt lành, đức độ', 'Cultivate good habits for lifelong growth.', 'Nuôi dưỡng thói quen tốt để tiến bộ suốt đời.', 'good deed', 'Sự lương thiện và chuẩn mực.'],
    ['Beautiful', '/ˈbjuː.tɪ.fəl/', 'tính từ', 'xinh đẹp, tươi đẹp', 'Nature displays beautiful harmony.', 'Thiên nhiên phô bày vẻ đẹp hài hòa.', 'beautiful scenery', 'Vẻ đẹp thẩm mỹ thuần khiết.'],
    ['Warm', '/wɔːm/', 'tính từ', 'ấm áp', 'Warm sunshine greets chilly mornings.', 'Nắng ấm chào đón những sớm mai se lạnh.', 'warm welcome', 'Nhiệt độ dễ chịu.'],
    ['Cold', '/kəʊld/', 'tính từ', 'lạnh giá', 'Wear a woolen coat in cold winter.', 'Hãy mặc áo khoác len trong mùa đông giá lạnh.', 'cold weather', 'Nhiệt độ thấp.'],
    ['Hot', '/hɒt/', 'tính từ', 'nóng bức, cay nồng', 'Drink cool water on a hot day.', 'Hãy uống nước mát vào một ngày nắng nóng.', 'hot tea', 'Nhiệt độ cao.'],
    ['Fast', '/fɑːst/', 'tính từ/phó từ', 'nhanh chóng', 'Cheetahs run remarkably fast.', 'Báo hoa mai chạy cực kỳ nhanh.', 'fast speed', 'Tốc độ cao trong thời gian ngắn.'],
    ['Slow', '/sləʊ/', 'tính từ/phó từ', 'chậm rãi', 'Slow and steady wins the race.', 'Chậm mà chắc sẽ giành chiến thắng cuộc đua.', 'slow down', 'Nhịp độ từ tốn bền bỉ.'],
    ['Easy', '/ˈiː.zi/', 'tính từ', 'dễ dàng, đơn giản', 'Practice makes difficult tasks easy.', 'Luyện tập biến những nhiệm vụ khó thành dễ dàng.', 'take it easy', 'Không đòi hỏi quá nhiều nỗ lực.'],
  ]}
];

// Let's create builders for A2, B1, B2, C1 similarly
console.log('Oxford A1 total:', englishVocab.reduce((acc, u) => acc + u.words.length, 0));
