import fs from 'fs';

// Oxford CEFR raw data
const enData = [
  // A1 (120 words)
  { level: 'A1', unit: 'Unit 1: Chào hỏi & Bản thân', words: [
    ['Hello', '/həˈləʊ/', 'exclamation', 'xin chào', 'Hello, nice to meet you!', 'Xin chào, rất vui được gặp bạn!'],
    ['Goodbye', '/ɡʊdˈbaɪ/', 'exclamation', 'tạm biệt', 'Goodbye, see you tomorrow.', 'Tạm biệt, hẹn gặp lại ngày mai.'],
    ['Name', '/neɪm/', 'noun', 'tên, danh xưng', 'What is your full name?', 'Tên đầy đủ của bạn là gì?'],
    ['Friend', '/frend/', 'noun', 'người bạn', 'She is my closest friend.', 'Cô ấy là người bạn thân nhất của tôi.'],
    ['Family', '/ˈfæm.əl.i/', 'noun', 'gia đình', 'I love spending time with my family.', 'Tôi thích dành thời gian bên gia đình.'],
    ['Father', '/ˈfɑː.ðər/', 'noun', 'bố, người cha', 'My father is an engineer.', 'Bố tôi là một kỹ sư.'],
    ['Mother', '/ˈmʌð.ər/', 'noun', 'mẹ, người mẹ', 'My mother cooks delicious meals.', 'Mẹ tôi nấu những bữa ăn rất ngon.'],
    ['Brother', '/ˈbrʌð.ər/', 'noun', 'anh trai, em trai', 'My brother is a high school student.', 'Anh trai tôi là một học sinh cấp ba.'],
    ['Sister', '/ˈsɪs.tər/', 'noun', 'chị gái, em gái', 'My sister loves playing piano.', 'Em gái tôi rất thích chơi đàn dương cầm.'],
    ['Child', '/tʃaɪld/', 'noun', 'đứa trẻ, con cái', 'The child is playing in the garden.', 'Đứa trẻ đang chơi trong vườn.'],
    ['Home', '/həʊm/', 'noun', 'ngôi nhà, tổ ấm', 'There is no place like home.', 'Không có nơi nào ấm áp như tổ ấm gia đình.'],
    ['House', '/haʊs/', 'noun', 'căn nhà', 'They live in a beautiful house.', 'Họ sống trong một ngôi nhà xinh đẹp.'],
    ['Room', '/ruːm/', 'noun', 'căn phòng', 'My room is clean and bright.', 'Phòng tôi rất sạch sẽ và sáng sủa.'],
    ['School', '/skuːl/', 'noun', 'trường học', 'Students walk to school every morning.', 'Học sinh đi bộ đến trường mỗi buổi sáng.'],
    ['Teacher', '/ˈtiː.tʃər/', 'noun', 'giáo viên, thầy cô', 'Our English teacher is very kind.', 'Giáo viên tiếng Anh của chúng tôi rất tốt bụng.'],
    ['Student', '/ˈstjuː.dənt/', 'noun', 'học sinh, sinh viên', 'He is a university student in Hanoi.', 'Cậu ấy là một sinh viên đại học ở Hà Nội.'],
    ['Book', '/bʊk/', 'noun', 'cuốn sách', 'I am reading an interesting book.', 'Tôi đang đọc một cuốn sách rất thú vị.'],
    ['Pen', '/pen/', 'noun', 'bút mực, bút viết', 'Can I borrow your pen for a minute?', 'Tôi có thể mượn bút của bạn một lát được không?'],
    ['Water', '/ˈwɔː.tər/', 'noun', 'nước uống', 'Drink enough water every day.', 'Hãy uống đủ nước mỗi ngày.'],
    ['Food', '/fuːd/', 'noun', 'thức ăn, thực phẩm', 'Vietnamese food is world-famous.', 'Ẩm thực Việt Nam nổi tiếng khắp thế giới.'],
    ['Bread', '/bred/', 'noun', 'bánh mì', 'I have bread and milk for breakfast.', 'Tôi ăn bánh mì và uống sữa cho bữa sáng.'],
    ['Apple', '/ˈæp.əl/', 'noun', 'quả táo', 'An apple a day keeps the doctor away.', 'Một quả táo mỗi ngày giúp tránh xa bệnh tật.'],
    ['Time', '/taɪm/', 'noun', 'thời gian, giờ', 'What time does the train arrive?', 'Mấy giờ chuyến tàu sẽ đến?'],
    ['Day', '/deɪ/', 'noun', 'ngày, ban ngày', 'Today is a wonderful sunny day.', 'Hôm nay là một ngày nắng đẹp tuyệt vời.'],
    ['Night', '/naɪt/', 'noun', 'đêm, ban đêm', 'Good night and sweet dreams.', 'Chúc bạn ngủ ngon và có những giấc mơ đẹp.'],
    ['Morning', '/ˈmɔː.nɪŋ/', 'noun', 'buổi sáng', 'I wake up at six in the morning.', 'Tôi thức dậy lúc sáu giờ sáng.'],
    ['Evening', '/ˈiːv.nɪŋ/', 'noun', 'buổi tối', 'We watch news in the evening.', 'Chúng tôi xem tin tức vào buổi tối.'],
    ['Today', '/təˈdeɪ/', 'noun/adv', 'hôm nay', 'Today is my birthday.', 'Hôm nay là sinh nhật của tôi.'],
    ['Tomorrow', '/təˈmɒr.əʊ/', 'noun/adv', 'ngày mai', 'We have an exam tomorrow.', 'Chúng tôi có một bài kiểm tra vào ngày mai.'],
    ['Yesterday', '/ˈjes.tə.deɪ/', 'noun/adv', 'hôm qua', 'Yesterday was cold and rainy.', 'Hôm qua trời lạnh và có mưa.'],
  ]},
  { level: 'A1', unit: 'Unit 2: Hành động & Sinh hoạt thường nhật', words: [
    ['Live', '/lɪv/', 'verb', 'sống, sinh sống', 'I live in a peaceful neighborhood.', 'Tôi sống trong một khu phố yên bình.'],
    ['Work', '/wɜːk/', 'verb/noun', 'làm việc, công việc', 'She works as a graphic designer.', 'Cô ấy làm việc như một nhà thiết kế đồ họa.'],
    ['Study', '/ˈstʌd.i/', 'verb/noun', 'học tập, nghiên cứu', 'He studies hard for the test.', 'Cậu ấy học tập chăm chỉ cho kỳ thi.'],
    ['Eat', '/iːt/', 'verb', 'ăn', 'We usually eat dinner at 7 PM.', 'Chúng tôi thường ăn tối lúc 7 giờ tối.'],
    ['Drink', '/drɪŋk/', 'verb', 'uống', 'I like to drink hot green tea.', 'Tôi thích uống trà xanh nóng.'],
    ['Sleep', '/sliːp/', 'verb', 'ngủ', 'Children should sleep eight hours a night.', 'Trẻ em nên ngủ tám tiếng mỗi đêm.'],
    ['Wake', '/weɪk/', 'verb', 'thức dậy', 'I wake up early on weekdays.', 'Tôi thức dậy sớm vào các ngày trong tuần.'],
    ['Walk', '/wɔːk/', 'verb', 'đi bộ, dạo bộ', 'We walk in the park after dinner.', 'Chúng tôi đi bộ trong công viên sau bữa tối.'],
    ['Run', '/rʌn/', 'verb', 'chạy', 'He runs five kilometers every morning.', 'Anh ấy chạy năm cây số mỗi buổi sáng.'],
    ['Speak', '/spiːk/', 'verb', 'nói, phát biểu', 'Can you speak English slowly, please?', 'Bạn có thể nói tiếng Anh chậm lại một chút được không?'],
    ['Listen', '/ˈlɪs.ən/', 'verb', 'lắng nghe', 'Listen carefully to the teacher.', 'Hãy lắng nghe cẩn thận lời giáo viên.'],
    ['Read', '/riːd/', 'verb', 'đọc', 'She loves to read novels before sleeping.', 'Cô ấy thích đọc tiểu thuyết trước khi đi ngủ.'],
    ['Write', '/raɪt/', 'verb', 'viết', 'Please write your name on the form.', 'Xin vui lòng viết tên của bạn vào mẫu đơn.'],
    ['Help', '/help/', 'verb/noun', 'giúp đỡ, sự trợ giúp', 'Thank you for your kind help.', 'Cảm ơn sự giúp đỡ ân cần của bạn.'],
    ['Buy', '/baɪ/', 'verb', 'mua', 'I need to buy some fresh vegetables.', 'Tôi cần mua một ít rau củ tươi.'],
    ['Sell', '/sel/', 'verb', 'bán', 'They sell fresh bread in this bakery.', 'Họ bán bánh mì tươi ở tiệm bánh này.'],
    ['Open', '/ˈəʊ.pən/', 'verb/adj', 'mở, đang mở', 'Please open the window for fresh air.', 'Xin hãy mở cửa sổ để đón không khí trong lành.'],
    ['Close', '/kləʊz/', 'verb/adj', 'đóng, khép lại', 'Remember to close the door when leaving.', 'Nhớ đóng cửa khi rời đi.'],
    ['Start', '/stɑːt/', 'verb', 'bắt đầu', 'The movie starts in ten minutes.', 'Bộ phim sẽ bắt đầu trong mười phút nữa.'],
    ['Finish', '/ˈfɪn.ɪʃ/', 'verb', 'kết thúc, hoàn thành', 'I will finish my homework soon.', 'Tôi sẽ sớm hoàn thành bài tập về nhà.'],
    ['Like', '/laɪk/', 'verb', 'thích', 'Do you like listening to acoustic music?', 'Bạn có thích nghe nhạc mộc không?'],
    ['Love', '/lʌv/', 'verb/noun', 'yêu thương, niềm yêu thích', 'They love traveling to the seaside.', 'Họ rất thích đi du lịch đến bờ biển.'],
    ['Need', '/niːd/', 'verb', 'cần, nhu cầu', 'I need to buy a notebook.', 'Tôi cần mua một quyển vở ghi chép.'],
    ['Want', '/wɒnt/', 'verb', 'muốn', 'Do you want a cup of coffee?', 'Bạn có muốn một tách cà phê không?'],
    ['Happy', '/ˈhæp.i/', 'adj', 'vui vẻ, hạnh phúc', 'We are very happy with the results.', 'Chúng tôi rất vui mừng với kết quả.'],
    ['Sad', '/sæd/', 'adj', 'buồn bã', 'She felt sad when her friend moved away.', 'Cô ấy cảm thấy buồn khi bạn chuyển đi xa.'],
    ['Big', '/bɪɡ/', 'adj', 'to lớn', 'London is a big and busy city.', 'Luân Đôn là một thành phố lớn và bận rộn.'],
    ['Small', '/smɔːl/', 'adj', 'nhỏ nhắn', 'They live in a small, cozy apartment.', 'Họ sống trong một căn hộ nhỏ ấm cúng.'],
    ['Good', '/ɡʊd/', 'adj', 'tốt, giỏi', 'He is a very good programmer.', 'Anh ấy là một lập trình viên rất giỏi.'],
    ['Bad', '/bæd/', 'adj', 'xấu, tồi tệ', 'Eating too much sugar is bad for your teeth.', 'Ăn quá nhiều đường rất có hại cho răng.'],
  ]},
  { level: 'A1', unit: 'Unit 3: Đồ vật, Màu sắc & Không gian', words: [
    ['Red', '/red/', 'adj/noun', 'màu đỏ', 'She wore a bright red dress.', 'Cô ấy mặc một chiếc váy màu đỏ tươi.'],
    ['Blue', '/bluː/', 'adj/noun', 'màu xanh da trời', 'The ocean is clear and blue.', 'Nước biển trong vắt và có màu xanh biếc.'],
    ['Green', '/ɡriːn/', 'adj/noun', 'màu xanh lá cây', 'The trees turn green in spring.', 'Cây cối đâm chồi xanh tươi vào mùa xuân.'],
    ['Yellow', '/ˈjel.əʊ/', 'adj/noun', 'màu vàng', 'Sunflowers are bright yellow.', 'Những bông hoa hướng dương có màu vàng rực.'],
    ['Black', '/blæk/', 'adj/noun', 'màu đen', 'He drives a sleek black car.', 'Anh ấy lái một chiếc xe màu đen sang trọng.'],
    ['White', '/waɪt/', 'adj/noun', 'màu trắng', 'Snow is pure and white.', 'Tuyết rơi trắng xóa và tinh khôi.'],
    ['Car', '/kɑːr/', 'noun', 'xe ô tô', 'He washes his car every weekend.', 'Anh ấy rửa xe ô tô vào mỗi cuối tuần.'],
    ['Bus', '/bʌs/', 'noun', 'xe buýt', 'Taking the bus saves money.', 'Đi xe buýt giúp tiết kiệm chi phí.'],
    ['Bicycle', '/ˈbaɪ.sɪ.kəl/', 'noun', 'xe đạp', 'She rides a bicycle along the river.', 'Cô ấy đạp xe đạp dọc theo bờ sông.'],
    ['Street', '/striːt/', 'noun', 'đường phố', 'The street is decorated with lanterns.', 'Con phố được trang hoàng bằng những chiếc đèn lồng.'],
    ['City', '/ˈsɪt.i/', 'noun', 'thành phố', 'Tokyo is a vibrant and modern city.', 'Tokyo là một thành phố sôi động và hiện đại.'],
    ['Country', '/ˈkʌn.tri/', 'noun', 'đất nước, vùng quê', 'Vietnam is a peaceful country.', 'Việt Nam là một đất nước thanh bình.'],
    ['Money', '/ˈmʌn.i/', 'noun', 'tiền bạc', 'Save some money for rainy days.', 'Hãy tiết kiệm một ít tiền cho những ngày khó khăn.'],
    ['Price', '/praɪs/', 'noun', 'giá cả', 'The price of vegetables is reasonable.', 'Giá của các loại rau rất hợp lý.'],
    ['Shop', '/ʃɒp/', 'noun/verb', 'cửa hàng, mua sắm', 'Let us go to the book shop.', 'Chúng ta cùng đi tới hiệu sách nhé.'],
    ['Market', '/ˈmɑː.kɪt/', 'noun', 'khu chợ', 'Local markets offer fresh seafood.', 'Các khu chợ địa phương cung cấp hải sản tươi sống.'],
    ['Table', '/ˈteɪ.bəl/', 'noun', 'cái bàn', 'Dinner is served on the table.', 'Bữa tối đã được dọn lên bàn.'],
    ['Chair', '/tʃeər/', 'noun', 'cái ghế', 'Please pull up a chair and sit down.', 'Xin hãy kéo một chiếc ghế và ngồi xuống.'],
    ['Door', '/dɔːr/', 'noun', 'cánh cửa', 'Someone is knocking at the front door.', 'Có ai đó đang gõ cửa trước.'],
    ['Window', '/ˈwɪn.dəʊ/', 'noun', 'cửa sổ', 'Look through the window at the garden.', 'Hãy nhìn qua cửa sổ ra phía khu vườn.'],
    ['Computer', '/kəmˈpjuː.tər/', 'noun', 'máy vi tính', 'Modern computers are extremely fast.', 'Máy tính hiện đại có tốc độ cực kỳ nhanh.'],
    ['Phone', '/fəʊn/', 'noun', 'điện thoại', 'My phone battery is low.', 'Pin điện thoại của tôi sắp cạn rồi.'],
    ['Clock', '/klɒk/', 'noun', 'đồng hồ treo tường', 'The clock on the wall ticks softly.', 'Chiếc đồng hồ trên tường kêu tích tắc êm dịu.'],
    ['Watch', '/wɒtʃ/', 'noun/verb', 'đồng hồ đeo tay, theo dõi', 'He wears a classic leather watch.', 'Anh ấy đeo một chiếc đồng hồ dây da cổ điển.'],
    ['Bag', '/bæɡ/', 'noun', 'túi xách, cặp sách', 'She carries a canvas bag to class.', 'Cô ấy mang theo một chiếc túi vải đi học.'],
    ['Clothes', '/kləʊðz/', 'noun', 'quần áo', 'Hang your clothes neatly in the wardrobe.', 'Hãy treo quần áo gọn gàng trong tủ.'],
    ['Shirt', '/ʃɜːt/', 'noun', 'áo sơ mi', 'He wore a clean white shirt.', 'Anh ấy mặc một chiếc áo sơ mi trắng tinh.'],
    ['Shoes', '/ʃuːz/', 'noun', 'đôi giày', 'Put on your running shoes.', 'Hãy mang giày chạy bộ vào nào.'],
    ['Hat', '/hæt/', 'noun', 'cái mũ, nón', 'Wear a hat to protect from the sun.', 'Hãy đội mũ để che nắng.'],
    ['Rain', '/reɪn/', 'noun/verb', 'cơn mưa, trời mưa', 'It started to rain heavily.', 'Trời bắt đầu đổ mưa như trút nước.'],
  ]},
  { level: 'A1', unit: 'Unit 4: Tự nhiên, Thời tiết & Con người', words: [
    ['Sun', '/sʌn/', 'noun', 'mặt trời', 'The sun rises in the east.', 'Mặt trời mọc ở hướng đông.'],
    ['Moon', '/muːn/', 'noun', 'mặt trăng', 'The full moon illuminates the lake.', 'Trăng tròn tỏa sáng lung linh trên mặt hồ.'],
    ['Star', '/stɑːr/', 'noun', 'ngôi sao', 'Thousands of stars shine in the night sky.', 'Hàng ngàn vì sao lấp lánh trên bầu trời đêm.'],
    ['Sky', '/skaɪ/', 'noun', 'bầu trời', 'The sky is clear and blue today.', 'Bầu trời hôm nay thật trong trẻo và xanh mát.'],
    ['Tree', '/triː/', 'noun', 'cây cối', 'Ancient trees provide cool shade.', 'Những cây cổ thụ tạo bóng râm mát rượi.'],
    ['Flower', '/flaʊ.ər/', 'noun', 'bông hoa', 'Roses are beautiful fragrant flowers.', 'Hoa hồng là loài hoa đẹp và ngát hương thơm.'],
    ['River', '/ˈrɪv.ər/', 'noun', 'dòng sông', 'Boats float gently down the river.', 'Những chiếc thuyền lững lờ trôi xuôi dòng sông.'],
    ['Sea', '/siː/', 'noun', 'biển cả', 'The sound of the sea is relaxing.', 'Âm thanh của biển cả thật thư thái.'],
    ['Dog', '/dɒɡ/', 'noun', 'con chó', 'The friendly dog wagged its tail.', 'Chú chó thân thiện vẫy đuôi mừng rỡ.'],
    ['Cat', '/kæt/', 'noun', 'con mèo', 'The cat curled up by the fireplace.', 'Chú mèo cuộn tròn ngủ bên cạnh lò sưởi.'],
    ['Bird', '/bɜːd/', 'noun', 'loài chim', 'Birds sing sweet melodies at dawn.', 'Những chú chim hót líu lo lúc bình minh.'],
    ['Fish', '/fɪʃ/', 'noun', 'con cá', 'Colorful fish swim in the aquarium.', 'Đàn cá đủ màu sắc bơi lội trong bể kính.'],
    ['Eye', '/aɪ/', 'noun', 'đôi mắt', 'Her eyes sparkle with curiosity.', 'Đôi mắt cô ấy lấp lánh sự tò mò.'],
    ['Ear', '/ɪər/', 'noun', 'tai', 'He whispered a secret in her ear.', 'Anh ấy thì thầm một bí mật vào tai cô ấy.'],
    ['Hand', '/hænd/', 'noun', 'bàn tay', 'They walked hand in hand along the shore.', 'Họ nắm tay nhau cùng đi dạo dọc bờ biển.'],
    ['Foot', '/fʊt/', 'noun', 'bàn chân', 'He dipped his foot into the cool stream.', 'Anh ấy nhúng chân vào dòng suối mát lạnh.'],
    ['Heart', '/hɑːt/', 'noun', 'trái tim', 'Her heart beat fast with excitement.', 'Trái tim cô ấy đập rộn ràng vì phấn khích.'],
    ['Head', '/hed/', 'noun', 'cái đầu', 'Nod your head if you understand.', 'Hãy gật đầu nếu bạn đã hiểu nhé.'],
    ['Face', '/feɪs/', 'noun', 'gương mặt', 'She washed her face with warm water.', 'Cô ấy rửa mặt bằng nước ấm.'],
    ['Smile', '/smaɪl/', 'verb/noun', 'nụ cười, mỉm cười', 'A warm smile can brighten anyone\'s day.', 'Một nụ cười ấm áp có thể làm bừng sáng cả ngày.'],
    ['Laugh', '/lɑːf/', 'verb', 'cười thành tiếng', 'The comedy made everyone laugh out loud.', 'Vở hài kịch khiến mọi người cười ồ lên.'],
    ['Cry', '/kraɪ/', 'verb', 'khóc', 'The baby cried for his milk.', 'Đứa bé khóc vì muốn uống sữa.'],
    ['Song', '/sɒŋ/', 'noun', 'bài hát', 'This song brings back nostalgic memories.', 'Bài hát này gợi lại nhiều kỷ niệm hoài niệm.'],
    ['Music', '/ˈmjuː.zɪk/', 'noun', 'âm nhạc', 'Soft music helps me focus on coding.', 'Nhạc nhẹ giúp tôi tập trung hơn khi lập trình.'],
    ['Game', '/ɡeɪm/', 'noun', 'trò chơi', 'Chess is an intellectual strategy game.', 'Cờ vua là một trò chơi chiến thuật trí tuệ.'],
    ['Sport', '/spɔːt/', 'noun', 'môn thể thao', 'Swimming is an excellent full-body sport.', 'Bơi lội là môn thể thao toàn thân tuyệt vời.'],
    ['Paper', '/ˈpeɪ.pər/', 'noun', 'giấy viết', 'He folded the paper into an origami crane.', 'Anh ấy gấp tờ giấy thành hình con hạc.'],
    ['Number', '/ˈnʌm.bər/', 'noun', 'con số', 'Choose your lucky number between 1 and 10.', 'Hãy chọn con số may mắn của bạn từ 1 đến 10.'],
    ['Letter', '/ˈlet.ər/', 'noun', 'lá thư, chữ cái', 'She wrote a heartfelt letter to her parents.', 'Cô ấy viết một lá thư chân tình gửi cho cha mẹ.'],
    ['Picture', '/ˈpɪk.tʃər/', 'noun', 'bức tranh, tấm ảnh', 'This picture captures our summer trip.', 'Bức ảnh này lưu lại chuyến đi mùa hè của chúng tôi.'],
  ]}
];

console.log('Oxford A1 prepared:', enData.reduce((acc, u) => acc + u.words.length, 0));
